//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_ASIENTOS_DT
    {
        public string ID { get; set; }
        public string AsientoID { get; set; }
        public string CuentaID { get; set; }
        public string SucursalID { get; set; }
        public bool Débito { get; set; }
        public decimal Valor { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string PCID { get; set; }
        public Nullable<decimal> Valor_Base { get; set; }
        public string CreadoPor { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string EditadoPor { get; set; }
        public string DivisiónID { get; set; }
    
        public virtual ACC_CUENTAS ACC_CUENTAS { get; set; }
    }
}
