//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_CUENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_CUENTAS()
        {
            this.ACC_ASIENTOS_DT = new HashSet<ACC_ASIENTOS_DT>();
            this.ACC_ASIENTOS_PLANTILLAS_DT = new HashSet<ACC_ASIENTOS_PLANTILLAS_DT>();
            this.ACC_ASIENTOS_DAY_DT = new HashSet<ACC_ASIENTOS_DAY_DT>();
            this.ACC_CUENTAS1 = new HashSet<ACC_CUENTAS>();
            this.BGT_CODIGOS_CUENTAS = new HashSet<BGT_CODIGOS_CUENTAS>();
            this.EMP_DEBITOS_RUBROS = new HashSet<EMP_DEBITOS_RUBROS>();
            this.EMP_ROLES_RUBROS = new HashSet<EMP_ROLES_RUBROS>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Clase { get; set; }
        public string Tipo { get; set; }
        public string Ruta { get; set; }
        public string Orden { get; set; }
        public bool Anulado { get; set; }
        public string PadreID { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string PCID { get; set; }
        public string SucursalID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string Presupuesto { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string CódigoRF { get; set; }
        public string F101 { get; set; }
        public bool IsEnlace { get; set; }
        public string Código_Alterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_ASIENTOS_DT> ACC_ASIENTOS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_ASIENTOS_PLANTILLAS_DT> ACC_ASIENTOS_PLANTILLAS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_ASIENTOS_DAY_DT> ACC_ASIENTOS_DAY_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_CUENTAS> ACC_CUENTAS1 { get; set; }
        public virtual ACC_CUENTAS ACC_CUENTAS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BGT_CODIGOS_CUENTAS> BGT_CODIGOS_CUENTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_DEBITOS_RUBROS> EMP_DEBITOS_RUBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ROLES_RUBROS> EMP_ROLES_RUBROS { get; set; }
    }
}
