//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_CUENTAS_BACKUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACC_CUENTAS_BACKUP()
        {
            this.ACC_CUENTAS_BACKUP1 = new HashSet<ACC_CUENTAS_BACKUP>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Clase { get; set; }
        public string Tipo { get; set; }
        public string Ruta { get; set; }
        public string Orden { get; set; }
        public bool Anulado { get; set; }
        public string PadreID { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string PCID { get; set; }
        public string SucursalID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string Presupuesto { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string CódigoRF { get; set; }
        public string F101 { get; set; }
        public bool IsEnlace { get; set; }
        public string Código_Alterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACC_CUENTAS_BACKUP> ACC_CUENTAS_BACKUP1 { get; set; }
        public virtual ACC_CUENTAS_BACKUP ACC_CUENTAS_BACKUP2 { get; set; }
    }
}
