//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_CREDITOS
    {
        public string ID { get; set; }
        public string AcreedorId { get; set; }
        public string AsientoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public decimal Valor_Base { get; set; }
        public string Nota { get; set; }
        public string DivisiónID { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDAte { get; set; }
        public string SucursalId { get; set; }
        public string PcId { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public string Tipo_ComprobanteID { get; set; }
        public string FactTipo_ComprobanteID { get; set; }
        public string Credito_tributarioID { get; set; }
        public string acrSerie { get; set; }
        public string acrSecuencia { get; set; }
        public string acrAutorizacion { get; set; }
        public string FactSerie { get; set; }
        public string FactSecuencia { get; set; }
        public string FactAutorizacion { get; set; }
        public Nullable<System.DateTime> FactFecha { get; set; }
        public Nullable<bool> Procesado_SRI { get; set; }
        public Nullable<System.DateTime> FechaND { get; set; }
        public Nullable<bool> ArchivoSRI { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string LiquidaciónID { get; set; }
        public bool Retenido { get; set; }
        public string TipoGastoID { get; set; }
    }
}
