//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_ACREEDORES_ANEXOS
    {
        public string ID { get; set; }
        public string ProveedorID { get; set; }
        public string Tipo { get; set; }
        public string Nombre { get; set; }
        public string Teléfonos { get; set; }
        public string Movil { get; set; }
        public string Email { get; set; }
    }
}
