//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_ACREEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACR_ACREEDORES()
        {
            this.ACR_RECIBOS = new HashSet<ACR_RECIBOS>();
            this.COM_FACTURAS = new HashSet<COM_FACTURAS>();
            this.COM_LIQUIDACIONES = new HashSet<COM_LIQUIDACIONES>();
            this.IMP_PEDIDOS = new HashSet<IMP_PEDIDOS>();
            this.IMP_PREPEDIDOS = new HashSet<IMP_PREPEDIDOS>();
        }
    
        public string ID { get; set; }
        public string GrupoID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Representante { get; set; }
        public string TérminoID { get; set; }
        public string ZonaID { get; set; }
        public string Teléfono1 { get; set; }
        public string Teléfono2 { get; set; }
        public string Teléfono3 { get; set; }
        public string Teléfono4 { get; set; }
        public string Dirección { get; set; }
        public string Email { get; set; }
        public string WWW { get; set; }
        public string Nota { get; set; }
        public string Ruc { get; set; }
        public bool RFuente { get; set; }
        public string Cédula { get; set; }
        public string Clase { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string acrAutorizacion { get; set; }
        public string acrSerie { get; set; }
        public string SecuenciaID { get; set; }
        public string Tipo_Identificación { get; set; }
        public string Tip_Identificacion { get; set; }
        public string TipoComprobanteID { get; set; }
        public string CréditoTributarioID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string TipoCuenta { get; set; }
        public string Cuenta { get; set; }
        public string BancoID { get; set; }
        public string CuentaID { get; set; }
        public string Pais { get; set; }
        public string TipoPago { get; set; }
        public Nullable<bool> IsContribuyenteEspecial { get; set; }
        public Nullable<bool> IsObligadoContabilidad { get; set; }
        public bool Relacionado { get; set; }
        public string RazonSocial { get; set; }
        public string TipoCliente { get; set; }
        public decimal Cupo { get; set; }
        public byte[] Foto { get; set; }
        public string Categoria { get; set; }
        public string EmailOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACR_RECIBOS> ACR_RECIBOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_FACTURAS> COM_FACTURAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_LIQUIDACIONES> COM_LIQUIDACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_PEDIDOS> IMP_PEDIDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_PREPEDIDOS> IMP_PREPEDIDOS { get; set; }
    }
}
