//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_RETENCIONES_DT
    {
        public string RetenciónID { get; set; }
        public string Factura { get; set; }
        public decimal BaseFuente { get; set; }
        public Nullable<decimal> Base { get; set; }
        public string Tipo_RFIR { get; set; }
        public decimal Tasa_RFIR { get; set; }
        public decimal Total_RFIR { get; set; }
        public string CuentaID_RFIR { get; set; }
        public decimal BaseIVA { get; set; }
        public string Tipo_RFIVA { get; set; }
        public decimal Tasa_RFIVA { get; set; }
        public decimal Total_RFIVA { get; set; }
        public string CuentaID_RFIVA { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string RetencionIVAID { get; set; }
        public string RetencionFuenteID { get; set; }
        public string TipoComprobante { get; set; }
        public string TipoDocumento { get; set; }
        public string FacturaID { get; set; }
        public string Preimpresa { get; set; }
        public string Tipofactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CódigoRFIR { get; set; }
        public string CódigoRFIVA { get; set; }
        public string RetenciónIVAID { get; set; }
        public string RetenciónFuenteID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ID { get; set; }
    
        public virtual ACR_RETENCIONES ACR_RETENCIONES { get; set; }
    }
}
