//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACR_RETENCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACR_RETENCIONES()
        {
            this.ACR_RETENCIONES_DEUDAS = new HashSet<ACR_RETENCIONES_DEUDAS>();
            this.ACR_RETENCIONES_DT = new HashSet<ACR_RETENCIONES_DT>();
        }
    
        public string ID { get; set; }
        public string AsientoID { get; set; }
        public string AcreedorID { get; set; }
        public string Número { get; set; }
        public string NúmeroRFIR { get; set; }
        public string NúmeroRFIVA { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_SRI { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
        public string Dirección { get; set; }
        public string Ruc { get; set; }
        public decimal ValorRFIR { get; set; }
        public decimal ValorRFIVA { get; set; }
        public string Nota { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<bool> Procesado_SRI { get; set; }
        public bool Anulado { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string TipoFactura { get; set; }
        public string FacturaID { get; set; }
        public string RetencionIVAID { get; set; }
        public string TipoIdentificación { get; set; }
        public string TipoRetención { get; set; }
        public string Serie { get; set; }
        public string Secuencia { get; set; }
        public string Autozización { get; set; }
        public string Validez { get; set; }
        public string RetencionFuenteID { get; set; }
        public string RetencionIvaServiciosID { get; set; }
        public Nullable<bool> Procesado_SRI_FUENTE { get; set; }
        public string Retención_Secuencia { get; set; }
        public string Autorización { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string Estado { get; set; }
        public string SRI_ACK { get; set; }
        public string SRI_DHA { get; set; }
        public Nullable<System.DateTime> Editadodate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACR_RETENCIONES_DEUDAS> ACR_RETENCIONES_DEUDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACR_RETENCIONES_DT> ACR_RETENCIONES_DT { get; set; }
    }
}
