//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_FACTURAS_DT
    {
        public string ID { get; set; }
        public string FacturaID { get; set; }
        public string ActivoID { get; set; }
        public string OrdenDTID { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
