//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_ORDENES
    {
        public string ID { get; set; }
        public string ProveedorID { get; set; }
        public string Detalle { get; set; }
        public string TérminoID { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string DivisiónID { get; set; }
        public string Nota { get; set; }
        public string Estado { get; set; }
        public bool Ingresado { get; set; }
        public bool Anulado { get; set; }
        public bool Facturado { get; set; }
        public string FacturadoPor { get; set; }
        public Nullable<System.DateTime> FacturadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
