//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_ORDENES_DT
    {
        public string ID { get; set; }
        public string OrdenID { get; set; }
        public string ActivoCode { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Costo { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public Nullable<decimal> Ingresado { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string CtaImpuestoID { get; set; }
        public string ItemImpuesto { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string TipoID { get; set; }
        public string GrupoID { get; set; }
        public string EmpleadoID { get; set; }
        public string DepartamentoID { get; set; }
        public string FunciónID { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string Procedencia { get; set; }
        public string Estado { get; set; }
        public bool Crédito_Fiscal { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<System.DateTime> Editadodate { get; set; }
    }
}
