//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AST_TAREAS
    {
        public string ID { get; set; }
        public string AsistenciaID { get; set; }
        public string ProductoID { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public string ClienteID { get; set; }
        public string EmpleadoID { get; set; }
        public string DivisiónID { get; set; }
        public decimal Cantidad { get; set; }
        public string Clase { get; set; }
        public string Detalle_Ex { get; set; }
        public string Empaque { get; set; }
        public decimal Factor { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public bool Procesado { get; set; }
        public string ProcesadoPor { get; set; }
        public Nullable<System.DateTime> ProcesadoDate { get; set; }
        public string ProcesadoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public bool Bloqueado { get; set; }
        public string BloqueadoPor { get; set; }
        public bool Facturado { get; set; }
        public string FacturadoPor { get; set; }
        public Nullable<System.DateTime> FacturadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Urgente { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    
        public virtual AST_ASISTENCIAS AST_ASISTENCIAS { get; set; }
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
