//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_EGRESOS_DATOS_CASH
    {
        public string EgresoID { get; set; }
        public string BancoCode { get; set; }
        public string TipoCuenta { get; set; }
        public string Cuenta { get; set; }
        public string Telefono { get; set; }
        public string ZonaID { get; set; }
        public string Email { get; set; }
        public System.DateTime CreadoDate { get; set; }
        public bool Exportado { get; set; }
        public bool ExportadoUpdate { get; set; }
    }
}
