//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_TRANSFERENCIAS
    {
        public string ID { get; set; }
        public string AsientoID { get; set; }
        public string CuentaID_Origen { get; set; }
        public string CuentaID_Destino { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string Número { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
        public string Dirección { get; set; }
        public string Cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Valor_Transferencia { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public Nullable<decimal> RFIVA { get; set; }
        public Nullable<decimal> RFIR { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public string Beneficiario { get; set; }
        public string RUC { get; set; }
        public bool Anulado { get; set; }
        public string Nota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string DivisiónID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string DepósitoID { get; set; }
        public Nullable<decimal> Adicional { get; set; }
        public Nullable<bool> Transferido { get; set; }
        public string RFIRID { get; set; }
        public string RfivaID { get; set; }
        public Nullable<decimal> BaseRFIva { get; set; }
        public Nullable<decimal> BaseRFIR { get; set; }
        public string AutorizaciónRF { get; set; }
        public string NúmeroRF { get; set; }
        public Nullable<decimal> Base_Comision { get; set; }
        public string ComisionID { get; set; }
        public Nullable<System.DateTime> FechaFact { get; set; }
        public string acrAutorización { get; set; }
        public string acrSerie { get; set; }
        public string acrSecuencia { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public Nullable<bool> Procesado { get; set; }
        public System.DateTime AprobadoDate { get; set; }
        public string AprobadoPor { get; set; }
        public string LiqTarjeta { get; set; }
        public bool Entregado { get; set; }
        public bool IsDébito { get; set; }
        public bool IsCargado { get; set; }
    }
}
