//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_CREDITOS_CUENTAS
    {
        public string CréditoID { get; set; }
        public string CuentaId { get; set; }
        public string Detalle { get; set; }
        public decimal Debe { get; set; }
        public Nullable<decimal> Haber { get; set; }
        public decimal Valor_Base { get; set; }
        public string CreadoPor { get; set; }
        public string SucursalId { get; set; }
        public string PcID { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public bool Débito { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string DivisiónID { get; set; }
        public string ID { get; set; }
    }
}
