//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_BANCOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAN_BANCOS()
        {
            this.BAN_CREDITOS = new HashSet<BAN_CREDITOS>();
            this.BAN_EGRESOS = new HashSet<BAN_EGRESOS>();
            this.BAN_INGRESOS = new HashSet<BAN_INGRESOS>();
            this.VEN_OPCIONES = new HashSet<VEN_OPCIONES>();
        }
    
        public string ID { get; set; }
        public string GrupoID { get; set; }
        public string Sucursal { get; set; }
        public string CtaMayorID { get; set; }
        public string CtaICCID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Cuenta { get; set; }
        public string Clase { get; set; }
        public string DivisaID { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string Formato_Comprobante { get; set; }
        public string Formato_Cheque { get; set; }
        public string WWW { get; set; }
        public decimal UltimoCheque { get; set; }
        public string CreadoPor { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string AnuladoPor { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string Ruc { get; set; }
        public Nullable<bool> PedirAprobación { get; set; }
        public string Formapago { get; set; }
        public string CódigoCashManagement { get; set; }
        public decimal MontoMáximo { get; set; }
        public string foto { get; set; }
        public byte[] FotoB { get; set; }
    
        public virtual BAN_GRUPOS BAN_GRUPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_CREDITOS> BAN_CREDITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_EGRESOS> BAN_EGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_INGRESOS> BAN_INGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_OPCIONES> VEN_OPCIONES { get; set; }
    }
}
