//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_INGRESOS_PINPAD
    {
        public string ID { get; set; }
        public string AID { get; set; }
        public string AplicacionEMV { get; set; }
        public string ARQC { get; set; }
        public string Filler1 { get; set; }
        public string FillerFinal { get; set; }
        public string Trama { get; set; }
        public string CodigoRespuestaAut { get; set; }
        public string Referencia { get; set; }
        public string Lote { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string Autorizacion { get; set; }
        public string MID { get; set; }
        public string MID2 { get; set; }
        public string TID { get; set; }
        public string PIN { get; set; }
        public string TSI { get; set; }
        public string TVR { get; set; }
        public string NombreAdquirente { get; set; }
        public string TarjetaHabiente { get; set; }
        public string NumeroTajeta { get; set; }
        public string Vencimiento { get; set; }
        public string ModoLectura { get; set; }
        public string RedAdquiriente { get; set; }
        public decimal BaseCero { get; set; }
        public decimal BaseIva { get; set; }
        public decimal ValorIva { get; set; }
        public decimal Total { get; set; }
        public decimal Interes { get; set; }
        public string ChipAppName { get; set; }
        public string Red { get; set; }
        public decimal TipoDiferido { get; set; }
        public decimal CardType { get; set; }
        public decimal PayType { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string PcID { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string Anuladopor { get; set; }
        public Nullable<System.DateTime> Anuladodate { get; set; }
        public string SucursalID { get; set; }
        public string Estado { get; set; }
        public decimal TermTime { get; set; }
        public decimal CodDiferido { get; set; }
        public decimal MesGracia { get; set; }
        public bool Exportado { get; set; }
        public bool ExportadoUpdate { get; set; }
    }
}
