//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_EGRESOS_PAGOS
    {
        public string EgresoID { get; set; }
        public System.DateTime FechaDeuda { get; set; }
        public System.DateTime Vencimiento { get; set; }
        public string Detalle { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalId { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ID { get; set; }
        public System.DateTime CreadoDate { get; set; }
    }
}
