//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_INGRESOS_TARJETAS
    {
        public string ID { get; set; }
        public string IngresoID { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public decimal Nuevo_Saldo { get; set; }
        public string CtaCxCID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> anulado { get; set; }
        public string anuladopor { get; set; }
        public Nullable<System.DateTime> anuladodate { get; set; }
        public string anuladonota { get; set; }
    }
}
