//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_PAPELETAS
    {
        public string ID { get; set; }
        public string AsientoID_Confirmado { get; set; }
        public string AsientoID_Procesado { get; set; }
        public string Tipo { get; set; }
        public string ClienteID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Papeleta { get; set; }
        public string BancoID { get; set; }
        public decimal Valor { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string Estado { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string ConfirmadoPor { get; set; }
        public Nullable<System.DateTime> ConfirmadoDate { get; set; }
        public string ProcesadoPor { get; set; }
        public Nullable<System.DateTime> ProcesadoDate { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> FechaConfirma { get; set; }
        public Nullable<decimal> RetenciónFuente { get; set; }
        public Nullable<decimal> RetenciónIVA { get; set; }
        public Nullable<bool> Impresa { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public string ZonaID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
