//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_EGRESOS_RETENCIONES
    {
        public string EgresoID { get; set; }
        public string Factura { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public Nullable<decimal> Base_Imponible { get; set; }
        public string Tipo_RFIR { get; set; }
        public Nullable<decimal> Tasa_RFIR { get; set; }
        public Nullable<decimal> Total_RFIR { get; set; }
        public string CuentaID_RFIR { get; set; }
        public string Tipo_RFIVA { get; set; }
        public Nullable<decimal> Tasa_RFIVA { get; set; }
        public Nullable<decimal> Total_RFIVA { get; set; }
        public string CuentaID_RFIVA { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ID { get; set; }
    }
}
