//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_INGRESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAN_INGRESOS()
        {
            this.BAN_INGRESOS_DT = new HashSet<BAN_INGRESOS_DT>();
        }
    
        public string ID { get; set; }
        public string BancoID { get; set; }
        public string AsientoID { get; set; }
        public string DeudorID { get; set; }
        public string PcID { get; set; }
        public string Número { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> RFIR { get; set; }
        public Nullable<decimal> RFIVA { get; set; }
        public decimal Valor { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> Faltante { get; set; }
        public Nullable<decimal> Sobrante { get; set; }
        public Nullable<decimal> Valor_Base { get; set; }
        public bool Anulado { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string CreadoPor { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string EditadoPor { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string DivisiónID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string OrdenID { get; set; }
        public string NumRecibo { get; set; }
        public string VendedorID { get; set; }
        public string AcreedorID { get; set; }
        public bool Cerrada { get; set; }
        public string MovUniqueId { get; set; }
        public string ClteCréditoID { get; set; }
        public string ClteDébitoID { get; set; }
    
        public virtual BAN_BANCOS BAN_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_INGRESOS_DT> BAN_INGRESOS_DT { get; set; }
    }
}
