//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_EGRESOS_ANTICIPOS_RUBROS
    {
        public string EgresoID { get; set; }
        public string EmpleadoId { get; set; }
        public string RubroID { get; set; }
        public string DocumentoID { get; set; }
        public string CuentaID { get; set; }
        public string CtaProvisiónID { get; set; }
        public string Clase { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Calculado { get; set; }
        public decimal Valor { get; set; }
        public string Variable { get; set; }
        public string Fórmula { get; set; }
        public bool Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
    }
}
