//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_DEPOSITOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAN_DEPOSITOS()
        {
            this.BAN_DEPOSITOS_DT = new HashSet<BAN_DEPOSITOS_DT>();
        }
    
        public string ID { get; set; }
        public string BancoID { get; set; }
        public string CajaID { get; set; }
        public string AsientoID { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string Número { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Detalle { get; set; }
        public bool Anulado { get; set; }
        public decimal Total { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public string Nota { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public string DivisaID2 { get; set; }
        public Nullable<decimal> Cambio2 { get; set; }
        public string Tipo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string EditadoPor { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<decimal> Diferencial { get; set; }
        public string DivisiónID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string NoPapeleta { get; set; }
        public Nullable<bool> Transferido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_DEPOSITOS_DT> BAN_DEPOSITOS_DT { get; set; }
    }
}
