//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BGT_PROVEEDORES_CATEGORIAS
    {
        public int ID { get; set; }
        public string ProveedorID { get; set; }
        public decimal Año { get; set; }
        public string Mes { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string CategoriaID { get; set; }
        public System.DateTime CreadoDate { get; set; }
        public bool Exportado { get; set; }
        public bool ExportadoUpdate { get; set; }
    }
}
