//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class citas
    {
        public int eventid { get; set; }
        public string subject { get; set; }
        public Nullable<int> importancelevel { get; set; }
        public string location { get; set; }
        public Nullable<int> scheduleid { get; set; }
        public string body { get; set; }
        public Nullable<System.DateTime> startdatetime { get; set; }
        public Nullable<System.DateTime> enddatetime { get; set; }
        public Nullable<byte> isalldayevent { get; set; }
        public Nullable<int> labelid { get; set; }
        public Nullable<byte> isprivate { get; set; }
        public Nullable<byte> ismeeting { get; set; }
    }
}
