//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_COTIZACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLI_COTIZACIONES()
        {
            this.CLI_COTIZACIONES_DT = new HashSet<CLI_COTIZACIONES_DT>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ClienteID { get; set; }
        public string Cliente { get; set; }
        public string VendedorID { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string Atentamente { get; set; }
        public string Validez { get; set; }
        public string TérminoID { get; set; }
        public string Detalle { get; set; }
        public string DivisiónID { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Nota { get; set; }
        public Nullable<bool> Facturado { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public string Aprobadopor { get; set; }
        public Nullable<System.DateTime> AprobadoDAte { get; set; }
        public string TituloID { get; set; }
        public string Entrega { get; set; }
        public string FormaPago { get; set; }
        public bool tarjeta { get; set; }
        public string BodegaID { get; set; }
        public decimal Financiero { get; set; }
        public string PlazoID { get; set; }
    
        public virtual CLI_CLIENTES CLI_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_COTIZACIONES_DT> CLI_COTIZACIONES_DT { get; set; }
    }
}
