//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_COBRANZAS_DT
    {
        public string ID { get; set; }
        public string ClienteID { get; set; }
        public string CobranzaID { get; set; }
        public string DeudaID { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Dif_Cambio { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public string RubroID { get; set; }
        public string CtaCxCID { get; set; }
        public Nullable<decimal> CambioDía { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<decimal> Ingresado { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public Nullable<decimal> Deposito { get; set; }
        public Nullable<decimal> RFIR { get; set; }
        public Nullable<decimal> RFIVA { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Afavor { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<System.DateTime> Editadodate { get; set; }
    }
}
