//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_CONTRATOS
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string ClienteID { get; set; }
        public string PropiedadID { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Nota { get; set; }
        public Nullable<bool> Indefinido { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string PcID { get; set; }
        public string SucursalID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<bool> Liquidado { get; set; }
        public Nullable<System.DateTime> LiquidadoDate { get; set; }
        public string LiquidadoPor { get; set; }
        public string EmpleadoID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<bool> Impresa { get; set; }
        public Nullable<bool> ClienteExistente { get; set; }
        public Nullable<System.DateTime> ExportadoUpdateDate { get; set; }
        public Nullable<decimal> Replicar { get; set; }
        public decimal Exportadocandidate { get; set; }
        public bool SRI { get; set; }
    }
}
