//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_GRUPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLI_GRUPOS()
        {
            this.CLI_CLIENTES = new HashSet<CLI_CLIENTES>();
        }
    
        public string ID { get; set; }
        public string PadreID { get; set; }
        public string PCID { get; set; }
        public string SucursalID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Orden { get; set; }
        public string Ruta { get; set; }
        public bool Anulado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Color { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> AplicaDescuentos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_CLIENTES> CLI_CLIENTES { get; set; }
    }
}
