//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_CONTRATOS_SERVICIOS
    {
        public string ID { get; set; }
        public string ContratoID { get; set; }
        public string ProductoID { get; set; }
        public bool Activo { get; set; }
        public string DivisaID { get; set; }
        public string Detalle_ex { get; set; }
        public string Referencia { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal Valor { get; set; }
        public string Frecuencia { get; set; }
        public string Mes { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalId { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<System.DateTime> ExportadoUpdateDate { get; set; }
        public Nullable<decimal> Replicar { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
