//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_LETRAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLI_LETRAS()
        {
            this.CLI_LETRAS_DEUDAS = new HashSet<CLI_LETRAS_DEUDAS>();
            this.CLI_LETRAS_DT = new HashSet<CLI_LETRAS_DT>();
        }
    
        public string ID { get; set; }
        public string ClienteID { get; set; }
        public string AsientoID { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string DivisiónID { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public decimal Valor { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    
        public virtual CLI_CLIENTES CLI_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_LETRAS_DEUDAS> CLI_LETRAS_DEUDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_LETRAS_DT> CLI_LETRAS_DT { get; set; }
    }
}
