//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLI_CLIENTES()
        {
            this.BAN_CHEQUES_PROTESTADOS = new HashSet<BAN_CHEQUES_PROTESTADOS>();
            this.CLI_CLIENTES_DEUDAS = new HashSet<CLI_CLIENTES_DEUDAS>();
            this.CLI_CLIENTES_OBSERVACIONES = new HashSet<CLI_CLIENTES_OBSERVACIONES>();
            this.CLI_COTIZACIONES = new HashSet<CLI_COTIZACIONES>();
            this.CLI_DEBITOS = new HashSet<CLI_DEBITOS>();
            this.CLI_LETRAS = new HashSet<CLI_LETRAS>();
            this.CLI_RECIBOS = new HashSet<CLI_RECIBOS>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string GrupoID { get; set; }
        public string ZonaID { get; set; }
        public string Vendedorid { get; set; }
        public string Clase { get; set; }
        public string TérminoID { get; set; }
        public string DivisiónID { get; set; }
        public string FormaPago { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
        public string Contacto { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public string Cédula { get; set; }
        public string Dirección { get; set; }
        public string Teléfono1 { get; set; }
        public string Teléfono2 { get; set; }
        public string Teléfono3 { get; set; }
        public string Teléfono4 { get; set; }
        public string Ruc { get; set; }
        public Nullable<decimal> SecuenciaRuta { get; set; }
        public string Ciudad { get; set; }
        public Nullable<decimal> Cupo { get; set; }
        public Nullable<decimal> CupoFactura { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Crédito { get; set; }
        public string Foto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Firma1 { get; set; }
        public string Firma2 { get; set; }
        public Nullable<System.DateTime> nacimiento { get; set; }
        public string Email { get; set; }
        public string Folder { get; set; }
        public string Calificación { get; set; }
        public string GNombre { get; set; }
        public string GCédula { get; set; }
        public string GEmpresa { get; set; }
        public string GZonaID { get; set; }
        public string GDirección { get; set; }
        public string GTeléfono1 { get; set; }
        public string GTeléfono2 { get; set; }
        public string GNota { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public string WWW { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string Nota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string SecuenciaID { get; set; }
        public Nullable<bool> IsClub { get; set; }
        public Nullable<bool> printSaldos { get; set; }
        public string CuentaID { get; set; }
        public Nullable<decimal> Díacorte { get; set; }
        public string ClienteID { get; set; }
        public Nullable<bool> EmpresaPrint { get; set; }
        public Nullable<bool> Publica { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string tipo_identificación { get; set; }
        public Nullable<bool> FactVencidas { get; set; }
        public Nullable<decimal> TasaRecargo { get; set; }
        public string XMLAnexos { get; set; }
        public string Tipo_Vivienda { get; set; }
        public Nullable<decimal> Valor_Vivienda { get; set; }
        public Nullable<decimal> Tiempo_Vivienda { get; set; }
        public Nullable<decimal> NoCargas { get; set; }
        public string Origen_Ingreso { get; set; }
        public string TipoVivienda { get; set; }
        public Nullable<decimal> ValorVivienda { get; set; }
        public Nullable<decimal> TiempoVivienda { get; set; }
        public string OrigenIngreso { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public string ClaseSujeto { get; set; }
        public string Visita { get; set; }
        public bool Relacionado { get; set; }
        public string EmailFE { get; set; }
        public string EMailCCFE { get; set; }
        public string RazonSocial { get; set; }
        public string TipoCliente { get; set; }
        public bool Movil { get; set; }
        public string MovUniqueId { get; set; }
        public decimal Longitud { get; set; }
        public decimal Latitud { get; set; }
        public bool PrecioPos { get; set; }
        public string cordenadas { get; set; }
        public string Coordenadas { get; set; }
        public string XMLDocumentos { get; set; }
        public decimal CupoDiferido { get; set; }
        public decimal CupoSobregiro { get; set; }
        public decimal NoDiferidos { get; set; }
        public bool IsAprobada { get; set; }
        public string WhatsApp { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public string JefeID { get; set; }
        public string Gerarquia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_CHEQUES_PROTESTADOS> BAN_CHEQUES_PROTESTADOS { get; set; }
        public virtual CLI_GRUPOS CLI_GRUPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_CLIENTES_DEUDAS> CLI_CLIENTES_DEUDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_CLIENTES_OBSERVACIONES> CLI_CLIENTES_OBSERVACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_COTIZACIONES> CLI_COTIZACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_DEBITOS> CLI_DEBITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_LETRAS> CLI_LETRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_RECIBOS> CLI_RECIBOS { get; set; }
    }
}
