//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_COTIZACIONES_DT
    {
        public string ID { get; set; }
        public string CotizaciónID { get; set; }
        public string ProductoID { get; set; }
        public string Nombre { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Detalle_Ex { get; set; }
        public string Clase { get; set; }
        public string Empaque { get; set; }
        public Nullable<bool> Embarque { get; set; }
        public string PrecioName { get; set; }
        public decimal Factor { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> anulado { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public decimal TasaFinanciero { get; set; }
        public decimal Financiero { get; set; }
    
        public virtual CLI_COTIZACIONES CLI_COTIZACIONES { get; set; }
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
