//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_CLIENTES_OBSERVACIONES
    {
        public string ClienteID { get; set; }
        public string DeID { get; set; }
        public string Nota { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string Hora { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
        public decimal Deuda { get; set; }
        public System.DateTime FechaProx { get; set; }
        public bool Proxllamada { get; set; }
        public decimal Recaudado { get; set; }
        public string ID { get; set; }
    
        public virtual CLI_CLIENTES CLI_CLIENTES { get; set; }
    }
}
