//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_COBRANZAS_INGRESOS
    {
        public string CobranzaID { get; set; }
        public string CobranzaDT_ID { get; set; }
        public string Tipo { get; set; }
        public string Número { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
        public string Girador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Valor_Base { get; set; }
        public Nullable<decimal> Dif_Cambio { get; set; }
        public Nullable<decimal> Depositado { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ID { get; set; }
    }
}
