//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLI_CLIENTES_DEUDAS
    {
        public string ID { get; set; }
        public string ClienteID { get; set; }
        public string DocumentoID { get; set; }
        public string AsientoID { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public decimal Valor { get; set; }
        public decimal ValorBase { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Vencimiento { get; set; }
        public string RubroID { get; set; }
        public string CtaCxCID { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public decimal Saldo { get; set; }
        public string Tipo { get; set; }
        public bool Crédito { get; set; }
        public bool Facturado { get; set; }
        public string DeudaID { get; set; }
        public Nullable<decimal> CambioDeuda { get; set; }
        public string VendedorID { get; set; }
        public bool Anulado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<bool> Retenido { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string MesArriendo { get; set; }
        public string ContratoID { get; set; }
        public Nullable<bool> Inmobiliaria { get; set; }
        public string MovUniqueId { get; set; }
        public decimal InteresAmortizado { get; set; }
        public decimal Interes { get; set; }
        public decimal InteresAcumulado { get; set; }
        public bool Intereses { get; set; }
        public bool PagoTardio { get; set; }
        public string DocumentoPA { get; set; }
        public string EmpresariaID { get; set; }
    
        public virtual CLI_CLIENTES CLI_CLIENTES { get; set; }
    }
}
