//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_ORDENES_DT
    {
        public string ID { get; set; }
        public string OrdenID { get; set; }
        public string ProductoID { get; set; }
        public decimal Stock { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Costo { get; set; }
        public decimal Precio { get; set; }
        public decimal Facturado { get; set; }
        public decimal Ingresado { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> TasaFinanciero { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> TasaEspecial { get; set; }
        public Nullable<decimal> Especial { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> TasaImpuestoICE { get; set; }
        public Nullable<decimal> ImpuestoIce { get; set; }
        public Nullable<decimal> TasaImpuestoVerde { get; set; }
        public Nullable<decimal> ImpuestoVErde { get; set; }
        public decimal Total { get; set; }
        public string Empaque { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public bool Promoción { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> TasaDescuento2 { get; set; }
        public Nullable<decimal> Descuento2 { get; set; }
        public Nullable<decimal> TasaEspecial2 { get; set; }
        public Nullable<decimal> Especial2 { get; set; }
        public Nullable<decimal> TasaEspecialC { get; set; }
        public Nullable<decimal> EspecialC { get; set; }
        public string Impuesto4ID { get; set; }
        public Nullable<decimal> TasaImpuesto4 { get; set; }
        public Nullable<decimal> Impuesto4 { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public Nullable<decimal> PVP { get; set; }
        public decimal xCada { get; set; }
        public decimal Regalo { get; set; }
        public decimal MeRegalo { get; set; }
        public bool EnUnidades { get; set; }
        public decimal CostoOld { get; set; }
        public decimal CostoPromo { get; set; }
        public string PromoID { get; set; }
    }
}
