//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_DEVOLUCIONES_DT
    {
        public string ID { get; set; }
        public string DevoluciónID { get; set; }
        public string FacturaID { get; set; }
        public string FacturaDT_ID { get; set; }
        public string ProductoID { get; set; }
        public string BodegaID { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> CantidadPromoción { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> TasaFinanciero { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> TasaEspecial { get; set; }
        public Nullable<decimal> Especial { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Empaque { get; set; }
        public string PrecioName { get; set; }
        public decimal Factor { get; set; }
        public string Detalle_Ex { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> ImpuestoICE { get; set; }
        public Nullable<decimal> ImpuestoVerde { get; set; }
        public Nullable<decimal> TasaImpuestoICE { get; set; }
        public Nullable<decimal> TasaImpuestoVerde { get; set; }
    
        public virtual COM_DEVOLUCIONES COM_DEVOLUCIONES { get; set; }
        public virtual COM_FACTURAS COM_FACTURAS { get; set; }
    }
}
