//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_FACTURAS_DT
    {
        public string ID { get; set; }
        public string FacturaID { get; set; }
        public string OrdenDTID { get; set; }
        public string ProductoID { get; set; }
        public string BodegaID { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> Devuelto { get; set; }
        public Nullable<decimal> DevueltoPromoción { get; set; }
        public Nullable<decimal> DecenaDe { get; set; }
        public Nullable<decimal> DocenaDe { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> TasaFinanciero { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> TasaEspecial { get; set; }
        public Nullable<decimal> Especial { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> TasaImpuestoIce { get; set; }
        public Nullable<decimal> ImpuestoIce { get; set; }
        public Nullable<decimal> TasaImpuestoVerde { get; set; }
        public Nullable<decimal> ImpuestoVerde { get; set; }
        public decimal Total { get; set; }
        public string Empaque { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public bool Promoción { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> PVP { get; set; }
        public Nullable<decimal> PVPNew { get; set; }
        public Nullable<bool> ActualizaPrecio { get; set; }
        public Nullable<decimal> CostoOld { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Lote { get; set; }
        public Nullable<decimal> CostoLista { get; set; }
        public decimal CantidadNC { get; set; }
        public decimal ValorNC { get; set; }
        public decimal PrecioNC { get; set; }
        public decimal xCada { get; set; }
        public decimal Regalo { get; set; }
        public decimal MeRegalo { get; set; }
        public bool EnUnidades { get; set; }
        public decimal CostoPromo { get; set; }
        public string PromoID { get; set; }
        public string OrdenID { get; set; }
        public Nullable<System.DateTime> Editadodate { get; set; }
        public decimal Ingresado { get; set; }
    
        public virtual COM_FACTURAS COM_FACTURAS { get; set; }
        public virtual INV_BODEGAS INV_BODEGAS { get; set; }
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
