//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_DEVOLUCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COM_DEVOLUCIONES()
        {
            this.COM_DEVOLUCIONES_DT = new HashSet<COM_DEVOLUCIONES_DT>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public string ProveedorID { get; set; }
        public string Detalle { get; set; }
        public string AsientoID { get; set; }
        public string FacturaID { get; set; }
        public string DivisiónID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string acrAutorizacion { get; set; }
        public string acrSerie { get; set; }
        public string acrSecuencia { get; set; }
        public Nullable<System.DateTime> FechaNC { get; set; }
        public string Credito_TributarioID { get; set; }
        public string Tipo_ComprobanteID { get; set; }
        public Nullable<bool> Procesado_SRI { get; set; }
        public Nullable<System.DateTime> FactFecha { get; set; }
        public Nullable<bool> Confirmado { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> ImpuestoICE { get; set; }
        public Nullable<decimal> ImpuestoVerde { get; set; }
        public decimal Compensacion { get; set; }
        public decimal BaseIva { get; set; }
        public decimal BaseCero { get; set; }
        public decimal BaseCons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_DEVOLUCIONES_DT> COM_DEVOLUCIONES_DT { get; set; }
    }
}
