//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COM_FACTURAS()
        {
            this.COM_DEVOLUCIONES_DT = new HashSet<COM_DEVOLUCIONES_DT>();
            this.COM_FACTURAS_DT = new HashSet<COM_FACTURAS_DT>();
        }
    
        public string ID { get; set; }
        public string ProveedorID { get; set; }
        public string AsientoID { get; set; }
        public string TérminoID { get; set; }
        public string DivisiónID { get; set; }
        public string OrdenID { get; set; }
        public string Detalle { get; set; }
        public string Número { get; set; }
        public string Tipo { get; set; }
        public string Referencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Recibido { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> ImpuestoIce { get; set; }
        public Nullable<decimal> ImpuestoVerde { get; set; }
        public decimal Total { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public bool Retenido { get; set; }
        public string acrAutorizacion { get; set; }
        public string acrSerie { get; set; }
        public string acrSecuencia { get; set; }
        public string Credito_tributarioID { get; set; }
        public string Tipo_comprobanteID { get; set; }
        public Nullable<System.DateTime> Fecha_documento { get; set; }
        public Nullable<System.DateTime> FechaFact { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string Recepción { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string SRI_ACK { get; set; }
        public decimal Compensacion { get; set; }
        public string Estado { get; set; }
        public string SRI_DHA { get; set; }
        public decimal ValorNC { get; set; }
        public string MotivoID { get; set; }
        public decimal PrecioNC { get; set; }
        public decimal RetFuente_Presuntivo { get; set; }
        public decimal RetIva_Presuntivo { get; set; }
        public decimal BaseIva { get; set; }
        public decimal BaseCero { get; set; }
        public decimal BaseExc { get; set; }
        public decimal BaseNoObj { get; set; }
        public decimal BaseCons { get; set; }
        public decimal Ingresado { get; set; }
    
        public virtual ACR_ACREEDORES ACR_ACREEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_DEVOLUCIONES_DT> COM_DEVOLUCIONES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_FACTURAS_DT> COM_FACTURAS_DT { get; set; }
    }
}
