//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DECIMOS_DT
    {
        public string DecimoID { get; set; }
        public string EmpleadoID { get; set; }
        public string CtaProvisiónID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Periodo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> Ajuste { get; set; }
        public Nullable<decimal> Calculado { get; set; }
        public Nullable<decimal> Dias { get; set; }
        public Nullable<decimal> Egresos { get; set; }
        public Nullable<decimal> Ingresos { get; set; }
        public string Cheque { get; set; }
        public bool PagarConCheque { get; set; }
        public string ID { get; set; }
    
        public virtual EMP_DECIMOS EMP_DECIMOS { get; set; }
        public virtual EMP_EMPLEADOS EMP_EMPLEADOS { get; set; }
    }
}
