//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ROLES_EMPLEADOS
    {
        public string RolID { get; set; }
        public string EmpleadoID { get; set; }
        public string CtaComisiónID { get; set; }
        public string LiquidaciónID { get; set; }
        public decimal Ingresos { get; set; }
        public decimal Egresos { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Provisiones { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<decimal> Jornal { get; set; }
        public Nullable<decimal> JornalM { get; set; }
        public Nullable<decimal> JornalV { get; set; }
        public Nullable<decimal> JornalN { get; set; }
        public Nullable<decimal> CargaHoraria { get; set; }
        public Nullable<decimal> CargaHorariaM { get; set; }
        public Nullable<decimal> CargaHorariaV { get; set; }
        public Nullable<decimal> CargaHorariaN { get; set; }
        public Nullable<decimal> Categoría { get; set; }
        public Nullable<decimal> Funcional { get; set; }
        public Nullable<decimal> Años { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public Nullable<decimal> Horas25 { get; set; }
        public Nullable<decimal> Horas50 { get; set; }
        public Nullable<decimal> Horas100 { get; set; }
        public Nullable<decimal> HorasM { get; set; }
        public Nullable<decimal> HorasV { get; set; }
        public Nullable<decimal> HorasN { get; set; }
        public string Detalle_Ex { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<bool> Liquidado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string NoCheque { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public string LiquidaciónTipo { get; set; }
    
        public virtual EMP_ROLES EMP_ROLES { get; set; }
    }
}
