//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_UTILIDADES
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string AsientoID { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string BancoID { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public string Cheque { get; set; }
        public string RubroID { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> Utilidad { get; set; }
        public Nullable<decimal> Utilidad_Empleado { get; set; }
        public Nullable<decimal> Utilidad_Carga { get; set; }
        public string Nota { get; set; }
        public bool Procesado { get; set; }
        public string DivisiónID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> UpdateExportado { get; set; }
        public Nullable<System.DateTime> UpdateExportadoDate { get; set; }
        public Nullable<decimal> Egresos { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
