//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_ROLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_ROLES()
        {
            this.EMP_ROLES_EMPLEADOS = new HashSet<EMP_ROLES_EMPLEADOS>();
            this.EMP_ROLES_RUBROS = new HashSet<EMP_ROLES_RUBROS>();
        }
    
        public string ID { get; set; }
        public string BancoID { get; set; }
        public string AsientoID { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Detalle { get; set; }
        public decimal Ingresos { get; set; }
        public decimal Egresos { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Provisiones { get; set; }
        public string Tipo { get; set; }
        public string Nota { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public bool Procesado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalId { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string Cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public Nullable<System.DateTime> AprobadoDate { get; set; }
        public string AprobadoPor { get; set; }
        public bool ChequeEntregado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ROLES_EMPLEADOS> EMP_ROLES_EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ROLES_RUBROS> EMP_ROLES_RUBROS { get; set; }
    }
}
