//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EMPLEADOS_HORAS
    {
        public decimal Año { get; set; }
        public string Mes { get; set; }
        public string EmpleadoID { get; set; }
        public Nullable<decimal> Dias { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public Nullable<decimal> Horas50 { get; set; }
        public Nullable<decimal> Horas25 { get; set; }
        public Nullable<decimal> Horas100 { get; set; }
        public Nullable<decimal> HorasVespertina { get; set; }
        public Nullable<decimal> HorasMatutina { get; set; }
        public Nullable<decimal> HorasNocturna { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public decimal DiasVC { get; set; }
    }
}
