//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DEBITOS_COMIDA
    {
        public string id { get; set; }
        public Nullable<decimal> costo_almuerzo { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public Nullable<System.DateTime> creadoDate { get; set; }
        public string creadoPor { get; set; }
        public string PcID { get; set; }
        public string SucursalID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
    }
}
