//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_EMPLEADOS()
        {
            this.BAN_EGRESOS_ANTICIPOS = new HashSet<BAN_EGRESOS_ANTICIPOS>();
            this.EMP_DECIMOS_DT = new HashSet<EMP_DECIMOS_DT>();
            this.EMP_DECLARACIONES_GASTOS = new HashSet<EMP_DECLARACIONES_GASTOS>();
            this.EMP_EMPLEADOS_DEUDAS = new HashSet<EMP_EMPLEADOS_DEUDAS>();
            this.EMP_ROLES_RUBROS = new HashSet<EMP_ROLES_RUBROS>();
            this.VEN_OPCIONES = new HashSet<VEN_OPCIONES>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string GrupoID { get; set; }
        public string ZonaID { get; set; }
        public string TablaID { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Cédula { get; set; }
        public string LibretaMilitar { get; set; }
        public string Cargo { get; set; }
        public string IESS { get; set; }
        public string Dirección { get; set; }
        public string Teléfono1 { get; set; }
        public string Teléfono2 { get; set; }
        public string Teléfono3 { get; set; }
        public string Sexo { get; set; }
        public bool Pastor { get; set; }
        public string Tipo_Cuenta { get; set; }
        public string Número_Cuenta { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string Profesión { get; set; }
        public string PadreID { get; set; }
        public decimal Sueldo { get; set; }
        public Nullable<decimal> Sueldo1 { get; set; }
        public Nullable<decimal> Sueldo2 { get; set; }
        public Nullable<decimal> Jornal { get; set; }
        public Nullable<decimal> JornalM { get; set; }
        public Nullable<decimal> JornalV { get; set; }
        public Nullable<decimal> JornalN { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public Nullable<decimal> HorasM { get; set; }
        public Nullable<decimal> HorasV { get; set; }
        public Nullable<decimal> HorasN { get; set; }
        public Nullable<decimal> PSueldo { get; set; }
        public Nullable<decimal> PSueldo1 { get; set; }
        public Nullable<decimal> PSueldo2 { get; set; }
        public Nullable<decimal> PJornal { get; set; }
        public Nullable<decimal> PJornalM { get; set; }
        public Nullable<decimal> PJornalV { get; set; }
        public Nullable<decimal> PJornalN { get; set; }
        public Nullable<decimal> Categoría { get; set; }
        public Nullable<decimal> Funcional { get; set; }
        public string DepartamentoID { get; set; }
        public string FunciónID { get; set; }
        public string CtaComisiónID { get; set; }
        public Nullable<decimal> TasaCobertura { get; set; }
        public Nullable<decimal> TasaVolumen { get; set; }
        public Nullable<decimal> TasaEspecial { get; set; }
        public string Ruta { get; set; }
        public string Orden { get; set; }
        public string email { get; set; }
        public byte[] Foto { get; set; }
        public string Clase { get; set; }
        public string Nota { get; set; }
        public bool Maternidad { get; set; }
        public Nullable<System.DateTime> Vacaciones { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> TasaMayorista { get; set; }
        public Nullable<decimal> TasaMinorista { get; set; }
        public Nullable<decimal> TasaNoTradicional { get; set; }
        public string Bancos { get; set; }
        public Nullable<decimal> BonoAntiguedad { get; set; }
        public string Calle { get; set; }
        public Nullable<decimal> Cargas_Familiares { get; set; }
        public string Ciudad { get; set; }
        public string DivisiónID { get; set; }
        public string LiquidaciónID { get; set; }
        public Nullable<bool> Liquidado { get; set; }
        public Nullable<System.DateTime> LiquidadoDate { get; set; }
        public string LiquidadoPor { get; set; }
        public string Num_Calle { get; set; }
        public Nullable<bool> PagoVacaciones { get; set; }
        public Nullable<bool> ProvisionaFR { get; set; }
        public string Rubrica { get; set; }
        public Nullable<decimal> Sueldo3 { get; set; }
        public Nullable<decimal> Sueldo4 { get; set; }
        public string tipo_Identificación { get; set; }
        public Nullable<bool> TomaVacaciones { get; set; }
        public Nullable<decimal> ImpuestoRenta { get; set; }
        public decimal Cupo { get; set; }
        public Nullable<bool> ProvisionaDE { get; set; }
        public string BodegaId { get; set; }
        public Nullable<bool> ControlarStock { get; set; }
        public string CodReloj { get; set; }
        public bool Movil { get; set; }
        public string Tipo { get; set; }
        public bool AportaConyuge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_EGRESOS_ANTICIPOS> BAN_EGRESOS_ANTICIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_DECIMOS_DT> EMP_DECIMOS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_DECLARACIONES_GASTOS> EMP_DECLARACIONES_GASTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_EMPLEADOS_DEUDAS> EMP_EMPLEADOS_DEUDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ROLES_RUBROS> EMP_ROLES_RUBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_OPCIONES> VEN_OPCIONES { get; set; }
    }
}
