//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_TABLAS_RUBROS
    {
        public string ID { get; set; }
        public string TablaID { get; set; }
        public string RubroID { get; set; }
        public string CuentaID { get; set; }
        public string CtaProvisiónID { get; set; }
        public bool Activo { get; set; }
        public string Variable { get; set; }
        public string DivisaID { get; set; }
        public decimal Valor { get; set; }
        public string Fórmula { get; set; }
        public string Frecuencia { get; set; }
        public string Mes { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalId { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    
        public virtual EMP_RUBROS EMP_RUBROS { get; set; }
        public virtual EMP_TABLAS EMP_TABLAS { get; set; }
    }
}
