//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_LIQUIDACION_DT
    {
        public string LiquidaciónID { get; set; }
        public string RubroID { get; set; }
        public string CuentaID { get; set; }
        public string CtaProvisiónID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> TotalP { get; set; }
        public Nullable<decimal> ValorAcumulado { get; set; }
        public Nullable<decimal> ValorProporcional { get; set; }
        public Nullable<decimal> ValorCalculado { get; set; }
        public Nullable<decimal> ValorAjuste { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string ID { get; set; }
    }
}
