//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DECIMOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_DECIMOS()
        {
            this.EMP_DECIMOS_DT = new HashSet<EMP_DECIMOS_DT>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public string BancoID { get; set; }
        public string RubroID { get; set; }
        public string AsientoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> IESS { get; set; }
        public string Nota { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public bool Procesado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public Nullable<decimal> AñosGanados { get; set; }
        public Nullable<decimal> Descuentos { get; set; }
        public Nullable<decimal> Diasvacaciones { get; set; }
        public string EmpleadoID { get; set; }
        public Nullable<decimal> FondoReserva { get; set; }
        public Nullable<decimal> Ingresos { get; set; }
        public Nullable<decimal> Liquidación { get; set; }
        public bool IsDebito { get; set; }
        public bool IsDébito { get; set; }
        public Nullable<bool> PagarEnRol { get; set; }
        public string AprobadoPor { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_DECIMOS_DT> EMP_DECIMOS_DT { get; set; }
        public virtual EMP_RUBROS EMP_RUBROS { get; set; }
    }
}
