//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_LIQUIDACION
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string EmpleadoID { get; set; }
        public string BancoID { get; set; }
        public string AsientoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Valor185 { get; set; }
        public Nullable<decimal> Valor188 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public bool Procesado { get; set; }
        public Nullable<decimal> Aportación { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> Patronal { get; set; }
        public Nullable<decimal> TipoLiquidacion { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<System.DateTime> UpdateExportadoDate { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<decimal> Antiguedad185 { get; set; }
        public Nullable<decimal> Antiguedad188 { get; set; }
        public Nullable<decimal> SueldoAjustado { get; set; }
        public Nullable<decimal> Antiguedad185Ajustado { get; set; }
        public Nullable<decimal> Antiguedad188Ajustado { get; set; }
        public Nullable<decimal> ValorVacacionesNoGozadas { get; set; }
        public Nullable<decimal> ValorMaternidad { get; set; }
        public string TablaID { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public decimal Exportadocandidate { get; set; }
        public decimal IECE { get; set; }
    }
}
