//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_RUBROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMP_RUBROS()
        {
            this.EMP_DEBITOS_RUBROS = new HashSet<EMP_DEBITOS_RUBROS>();
            this.EMP_DECIMOS = new HashSet<EMP_DECIMOS>();
            this.EMP_EMPLEADOS_DEUDAS = new HashSet<EMP_EMPLEADOS_DEUDAS>();
            this.EMP_ROLES_RUBROS = new HashSet<EMP_ROLES_RUBROS>();
            this.EMP_TABLAS_RUBROS = new HashSet<EMP_TABLAS_RUBROS>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string CtaDebeID { get; set; }
        public string CtaHaberID { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<bool> Liquidación { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> AportableIESS { get; set; }
        public Nullable<decimal> MesPago { get; set; }
        public Nullable<bool> Remuneracion { get; set; }
        public string Alias { get; set; }
        public decimal Orden { get; set; }
        public bool Vacaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_DEBITOS_RUBROS> EMP_DEBITOS_RUBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_DECIMOS> EMP_DECIMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_EMPLEADOS_DEUDAS> EMP_EMPLEADOS_DEUDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_ROLES_RUBROS> EMP_ROLES_RUBROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_TABLAS_RUBROS> EMP_TABLAS_RUBROS { get; set; }
    }
}
