//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EMPLEADOS_HISTORIAL
    {
        public string EmpleadoID { get; set; }
        public string Nombres_old { get; set; }
        public string Nombres_New { get; set; }
        public Nullable<decimal> Sueldo_old { get; set; }
        public Nullable<decimal> Sueldo_new { get; set; }
        public string Direccion_old { get; set; }
        public string Direccion_New { get; set; }
        public string Cedula_old { get; set; }
        public string Cedula_New { get; set; }
        public string Cuenta_old { get; set; }
        public string Cuenta_New { get; set; }
        public string tipocta_oldID { get; set; }
        public string tipocta_NewID { get; set; }
        public string Departamento_oldID { get; set; }
        public string Departamento_NewID { get; set; }
        public string Funcional_oldID { get; set; }
        public string Funcional_NewID { get; set; }
        public string Tabla_oldID { get; set; }
        public string Tabla_NewID { get; set; }
        public string Cargo_oldID { get; set; }
        public string Cargo_NewID { get; set; }
        public string cc_oldID { get; set; }
        public string cc_NewID { get; set; }
        public Nullable<System.DateTime> FechaIngreso_New { get; set; }
        public Nullable<System.DateTime> FechaIngreso_Old { get; set; }
        public string Nota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public string SucursalID { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string ID { get; set; }
    }
}
