//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_MARCADAS_DT
    {
        public string CodEmpleado { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Marcadas { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string PcID { get; set; }
        public string ID { get; set; }
        public bool Exportado { get; set; }
        public bool ExportadoUpdate { get; set; }
    }
}
