//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DECIMOS_PROVISIONES
    {
        public string DécimoID { get; set; }
        public string Provisión { get; set; }
        public string CuentaID { get; set; }
        public string CtaProvisiónID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string SucursalId { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ProvisiónID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<bool> Liquidado { get; set; }
        public string LiquidaciónID { get; set; }
        public string LiquidaciónTipo { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string ID { get; set; }
    }
}
