//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_UTILIDADES_DT
    {
        public string UtilidadID { get; set; }
        public string EmpleadoID { get; set; }
        public Nullable<decimal> Dias_Trabajados { get; set; }
        public Nullable<decimal> No_Cargas { get; set; }
        public Nullable<decimal> Cargas_DTrabajados { get; set; }
        public Nullable<decimal> Utilidad_Empleado { get; set; }
        public Nullable<decimal> Utilidad_Carga { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> UpdateExportado { get; set; }
        public Nullable<System.DateTime> UpdateExportadoDate { get; set; }
        public Nullable<decimal> Replicar { get; set; }
        public Nullable<decimal> Egresos { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<bool> EmpleadoAnulado { get; set; }
        public Nullable<bool> PagarConCheque { get; set; }
        public string Cheque { get; set; }
        public Nullable<decimal> Utilidad_EmpleadoCalculado { get; set; }
        public Nullable<decimal> Utilidad_CargaCalculado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string ID { get; set; }
    }
}
