//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_COMISIONES_PAGOS
    {
        public string DeudaID { get; set; }
        public string DocumentoID { get; set; }
        public string AsientoID { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public decimal Valor { get; set; }
        public decimal Dividendo { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ID { get; set; }
    }
}
