//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_DECLARACIONES_GASTOS
    {
        public string ID { get; set; }
        public string EmpleadoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<decimal> AñoFiscal { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> IngresosEmpleador { get; set; }
        public Nullable<decimal> IngresosOtrosEmpleadores { get; set; }
        public Nullable<decimal> TotalIngresos { get; set; }
        public Nullable<decimal> GastosAlimentacion { get; set; }
        public Nullable<decimal> GastosEducacion { get; set; }
        public Nullable<decimal> GastosSalud { get; set; }
        public Nullable<decimal> GastosVestimenta { get; set; }
        public Nullable<decimal> GastosVivienda { get; set; }
        public Nullable<decimal> TotalEgresos { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> IessOtrosEmpleadores { get; set; }
        public Nullable<decimal> ValorIR { get; set; }
        public Nullable<decimal> CuotaIR { get; set; }
        public decimal Exportadocandidate { get; set; }
    
        public virtual EMP_EMPLEADOS EMP_EMPLEADOS { get; set; }
    }
}
