//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_EMPLEADOS_CARGAS
    {
        public string EmpleadoID { get; set; }
        public Nullable<decimal> Edad { get; set; }
        public string Sexo { get; set; }
        public string Nombres { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string cédula { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nivel { get; set; }
        public string Ocupación { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<bool> Carga { get; set; }
        public string TipoCarga { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string ID { get; set; }
    }
}
