//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoTECKSoftware_LabelPrinter
    {
        public int ID { get; set; }
        public int PrinterID { get; set; }
        public string LabelName { get; set; }
        public string LabelFormat { get; set; }
        public Nullable<bool> Activated { get; set; }
    }
}
