//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PEDIDOS_MASTER
    {
        public string ID { get; set; }
        public string ProveedorID { get; set; }
        public string Number { get; set; }
        public string Referencia { get; set; }
        public string Detalle { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Despacho { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre { get; set; }
        public string TipoTransporte { get; set; }
        public string INCOTERMS { get; set; }
        public string PtoEmbarque { get; set; }
        public string PtoLlegada { get; set; }
        public string FormaPago { get; set; }
        public string FormaPagoID { get; set; }
        public Nullable<decimal> TotalPedido { get; set; }
        public Nullable<decimal> GastosAdicionales { get; set; }
        public Nullable<decimal> TotalGeneral { get; set; }
        public Nullable<decimal> Despachos { get; set; }
        public Nullable<decimal> ValorPendiente { get; set; }
        public Nullable<decimal> PagoAdelantado { get; set; }
        public string SucursalID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal ExportadoCandidate { get; set; }
    }
}
