//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PEDIDOS_MASTER_DT
    {
        public string ID { get; set; }
        public string PMasterID { get; set; }
        public string ProductoID { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> Despachado { get; set; }
        public decimal CostoCompra { get; set; }
        public Nullable<System.DateTime> FDespacho { get; set; }
        public string PartidaID { get; set; }
        public string Partida { get; set; }
        public Nullable<decimal> Arancel { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Fodinfa { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal ExportadoCandidate { get; set; }
    }
}
