//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PEDIDOS_EMPAQUES
    {
        public string PedidoID { get; set; }
        public string PedidoDT_ID { get; set; }
        public string ProductoID { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Costo { get; set; }
        public string EmpaqueID { get; set; }
        public decimal Factor { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal ExportadoCandidate { get; set; }
        public string ID { get; set; }
    }
}
