//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PREPEDIDOS_DT
    {
        public string ID { get; set; }
        public string PedidoID { get; set; }
        public string ProductoID { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public Nullable<decimal> Ingresado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Empaque { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> CostoFinal { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Precio_Bruto { get; set; }
        public decimal Ordenado { get; set; }
        public decimal CostoIngresado { get; set; }
        public string Nombre { get; set; }
        public decimal Precio_CIF { get; set; }
        public decimal Precio_Verificadora { get; set; }
        public decimal Volumen { get; set; }
        public bool NewPro { get; set; }
        public string OrdenDTID { get; set; }
    
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
