//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_LIQUIDACION_PEDIDOS
    {
        public string LiquidaciónID { get; set; }
        public string PedidoID { get; set; }
        public string ProveedorID { get; set; }
        public Nullable<decimal> Utilidad { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public string Detalle { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public string Estado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string ID { get; set; }
    
        public virtual IMP_PEDIDOS IMP_PEDIDOS { get; set; }
    }
}
