//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PROJECCION_DT
    {
        public string ID { get; set; }
        public string OrdenID { get; set; }
        public string ProductoID { get; set; }
        public decimal Cantidad { get; set; }
        public string Partida { get; set; }
        public Nullable<decimal> TasaADV { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public decimal PrecioNew { get; set; }
        public decimal TotalPrecio { get; set; }
        public Nullable<decimal> TasaOrigen { get; set; }
        public decimal TotalOrigen { get; set; }
        public decimal TotalFOB { get; set; }
        public Nullable<decimal> TasaDistrib { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        public Nullable<decimal> CIF { get; set; }
        public Nullable<decimal> AdValoren { get; set; }
        public Nullable<decimal> Base { get; set; }
        public decimal FodinFA { get; set; }
        public decimal ImpuestoAD { get; set; }
        public Nullable<decimal> CIF_Aduana { get; set; }
        public decimal IvaFlete { get; set; }
        public decimal IvaAduana { get; set; }
        public Nullable<decimal> Flete { get; set; }
        public decimal GastoOri { get; set; }
        public decimal GastoLoc { get; set; }
        public decimal CostoTotal { get; set; }
        public decimal CostoTotalIva { get; set; }
        public decimal CostoUnitario { get; set; }
        public decimal CostoUnitarioIva { get; set; }
        public Nullable<decimal> PVPSugerido { get; set; }
        public Nullable<decimal> PVPSugeridoIva { get; set; }
        public Nullable<decimal> PVP { get; set; }
        public Nullable<decimal> Ajuste { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public decimal Cert_Origen { get; set; }
    }
}
