//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_PEDIDOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMP_PEDIDOS()
        {
            this.IMP_LIQUIDACION = new HashSet<IMP_LIQUIDACION>();
            this.IMP_LIQUIDACION_DT = new HashSet<IMP_LIQUIDACION_DT>();
            this.IMP_LIQUIDACION_PEDIDOS = new HashSet<IMP_LIQUIDACION_PEDIDOS>();
            this.IMP_PEDIDOS_DT = new HashSet<IMP_PEDIDOS_DT>();
        }
    
        public string ID { get; set; }
        public string ProveedorID { get; set; }
        public string AsientoFacturarID { get; set; }
        public string AsientoLiquidarID { get; set; }
        public Nullable<System.DateTime> FechaLlegada { get; set; }
        public Nullable<System.DateTime> EntregaDocumento { get; set; }
        public string Banco { get; set; }
        public string Cobranza { get; set; }
        public string Pedido { get; set; }
        public string TérminoID { get; set; }
        public string DivisiónID { get; set; }
        public string Detalle { get; set; }
        public string Número { get; set; }
        public Nullable<decimal> TasaRent { get; set; }
        public string Verificadora { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> TipoImport { get; set; }
        public string Referencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaFacturado { get; set; }
        public Nullable<System.DateTime> FechaLiquidado { get; set; }
        public Nullable<decimal> ValorFOB { get; set; }
        public Nullable<decimal> ValorFlete { get; set; }
        public Nullable<decimal> Ajuste { get; set; }
        public Nullable<decimal> ValorCF { get; set; }
        public Nullable<System.DateTime> Embarque { get; set; }
        public string Seguro { get; set; }
        public Nullable<decimal> Flete_Verif { get; set; }
        public Nullable<decimal> Seguro_Verif { get; set; }
        public string Contenedor { get; set; }
        public string Empaque { get; set; }
        public string Origen { get; set; }
        public string Puerto { get; set; }
        public string Contenido { get; set; }
        public string Transporte { get; set; }
        public string BL { get; set; }
        public Nullable<System.DateTime> Recibido { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> ValFlete { get; set; }
        public Nullable<decimal> ValSeguro { get; set; }
        public Nullable<decimal> Gastos { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string BodegaID { get; set; }
        public string Nota { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Liquidado { get; set; }
        public string DespachadorID { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string Inspección { get; set; }
        public string NoContenedor { get; set; }
        public Nullable<decimal> TasaDesc { get; set; }
        public string PESO { get; set; }
        public Nullable<bool> Impresa { get; set; }
        public string DUI { get; set; }
        public string NotaPedido { get; set; }
        public string CertInsp1 { get; set; }
        public string CertInsp2 { get; set; }
        public Nullable<decimal> ValGastoDespacho { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal ExportadoCandidate { get; set; }
        public string Clase { get; set; }
        public string CondicionesID { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<System.DateTime> FechaEmbarque { get; set; }
        public Nullable<decimal> ingresado { get; set; }
        public string Marcas { get; set; }
        public string OrdenPedidoID { get; set; }
        public string PaisOrigen { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public string PuertoEmbarque { get; set; }
        public string PuertoLlegada { get; set; }
        public string Refrendo { get; set; }
        public string Secuencia { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> TasaSeguro { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public string departamentoid { get; set; }
        public string OrdenID { get; set; }
        public string XMLDocumentos { get; set; }
    
        public virtual ACR_ACREEDORES ACR_ACREEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_LIQUIDACION> IMP_LIQUIDACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_LIQUIDACION_DT> IMP_LIQUIDACION_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_LIQUIDACION_PEDIDOS> IMP_LIQUIDACION_PEDIDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_PEDIDOS_DT> IMP_PEDIDOS_DT { get; set; }
    }
}
