//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_LIQUIDACION
    {
        public string ID { get; set; }
        public string AsientoID { get; set; }
        public string AsientoLiquidarID { get; set; }
        public Nullable<System.DateTime> FechaLiquidado { get; set; }
        public string Negociación { get; set; }
        public string PedidoID { get; set; }
        public string DivisiónID { get; set; }
        public string IngresoID { get; set; }
        public string BodegaID { get; set; }
        public Nullable<System.DateTime> Embarque { get; set; }
        public string Empaque { get; set; }
        public string Origen { get; set; }
        public string Seguro { get; set; }
        public string Detalle { get; set; }
        public string Número { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Total { get; set; }
        public decimal Valor { get; set; }
        public string Nota { get; set; }
        public string Peso { get; set; }
        public string Pago { get; set; }
        public Nullable<decimal> PorcUtilidad { get; set; }
        public Nullable<decimal> PorcAveria { get; set; }
        public Nullable<decimal> ValFlete { get; set; }
        public Nullable<decimal> ValSeguro { get; set; }
        public Nullable<decimal> Gastos { get; set; }
        public string Puerto { get; set; }
        public string Transporte { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<bool> Impresa { get; set; }
        public string Estado { get; set; }
        public string Referencia { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal ExportadoCandidate { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<bool> embarcado { get; set; }
        public string TContenedor { get; set; }
        public string NoContenedor { get; set; }
        public string Contenido { get; set; }
        public string NoInspección { get; set; }
        public string BL { get; set; }
        public string Buque { get; set; }
        public string DUI { get; set; }
        public Nullable<decimal> Seguro_Verif { get; set; }
        public Nullable<decimal> Flete_Verif { get; set; }
        public string Verificadora { get; set; }
        public string TérminoID { get; set; }
        public Nullable<decimal> ValorTransformacion { get; set; }
        public decimal TipoImport { get; set; }
        public decimal TipoFlete { get; set; }
    
        public virtual IMP_PEDIDOS IMP_PEDIDOS { get; set; }
    }
}
