//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMP_LIQUIDACION_DT
    {
        public string ID { get; set; }
        public string LiquidaciónID { get; set; }
        public string PedidoID { get; set; }
        public string PedidoDTID { get; set; }
        public string ProveedorID { get; set; }
        public string ProductoID { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public Nullable<decimal> Ingresado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioBase { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Utilidad { get; set; }
        public string Empaque { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> CostoFinal { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> NewPrecio1 { get; set; }
        public Nullable<decimal> NewPrecio2 { get; set; }
        public Nullable<decimal> NewPrecio3 { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Precio_CIF { get; set; }
        public Nullable<decimal> Precio_Verificadora { get; set; }
        public Nullable<bool> ExportadoUpdate { get; set; }
        public Nullable<bool> Marcado { get; set; }
        public string bodegaid { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<decimal> exportado { get; set; }
        public decimal ValorISD { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string Lote { get; set; }
        public decimal Valor_Liberado { get; set; }
    
        public virtual IMP_PEDIDOS IMP_PEDIDOS { get; set; }
        public virtual IMP_PEDIDOS_DT IMP_PEDIDOS_DT { get; set; }
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
