//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PRODUCTOS_LOTES
    {
        public string ProductoID { get; set; }
        public string Lote { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Fabricacion { get; set; }
        public System.DateTime Caducidad { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public bool Anulado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string ProveedorID { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportado { get; set; }
    }
}
