//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_PRODUCTOS()
        {
            this.ACR_DEBITOS_PRODUCTOS = new HashSet<ACR_DEBITOS_PRODUCTOS>();
            this.AST_TAREAS = new HashSet<AST_TAREAS>();
            this.CLI_CREDITOS_PRODUCTOS = new HashSet<CLI_CREDITOS_PRODUCTOS>();
            this.COM_FACTURAS_DT = new HashSet<COM_FACTURAS_DT>();
            this.COM_LIQUIDACIONES_DT = new HashSet<COM_LIQUIDACIONES_DT>();
            this.EXP_FACTURAS_DT = new HashSet<EXP_FACTURAS_DT>();
            this.EXP_ORDENES_DT = new HashSet<EXP_ORDENES_DT>();
            this.IMP_LIQUIDACION_DT = new HashSet<IMP_LIQUIDACION_DT>();
            this.IMP_PEDIDOS_DT = new HashSet<IMP_PEDIDOS_DT>();
            this.IMP_PREPEDIDOS_DT = new HashSet<IMP_PREPEDIDOS_DT>();
            this.INV_COMBOS_COMPONENTES = new HashSet<INV_COMBOS_COMPONENTES>();
            this.INV_CONTEO_DT = new HashSet<INV_CONTEO_DT>();
            this.INV_EGRESOS_PRODUCTOS = new HashSet<INV_EGRESOS_PRODUCTOS>();
            this.INV_PRECIOS_DT = new HashSet<INV_PRECIOS_DT>();
            this.CLI_COTIZACIONES_DT = new HashSet<CLI_COTIZACIONES_DT>();
            this.COM_FACTURAS_LOTE_UBICACIONES = new HashSet<COM_FACTURAS_LOTE_UBICACIONES>();
            this.INV_FISICO_PRODUCTOS = new HashSet<INV_FISICO_PRODUCTOS>();
            this.INV_INGRESOS_LOTE_UBICACIONES = new HashSet<INV_INGRESOS_LOTE_UBICACIONES>();
            this.INV_PRODUCTOS_CARDEX_DAY = new HashSet<INV_PRODUCTOS_CARDEX_DAY>();
            this.INV_PRODUCTOS_CARDEX = new HashSet<INV_PRODUCTOS_CARDEX>();
            this.INV_PRODUCTOS_EXHIBICION = new HashSet<INV_PRODUCTOS_EXHIBICION>();
            this.INV_PRODUCTOS_MINIMOS = new HashSet<INV_PRODUCTOS_MINIMOS>();
            this.INV_PRODUCTOS_PRECIOS = new HashSet<INV_PRODUCTOS_PRECIOS>();
            this.INV_PRODUCTOS_PROMOCIONES = new HashSet<INV_PRODUCTOS_PROMOCIONES>();
            this.INV_PRODUCTOS_UBICACIONES = new HashSet<INV_PRODUCTOS_UBICACIONES>();
            this.INV_PROMOCIONES_DT = new HashSet<INV_PROMOCIONES_DT>();
            this.INV_TRANSFERENCIAS_DT = new HashSet<INV_TRANSFERENCIAS_DT>();
            this.SRV_EGRESOS_PRODUCTOS = new HashSet<SRV_EGRESOS_PRODUCTOS>();
            this.VEN_CONCILIACION_DT = new HashSet<VEN_CONCILIACION_DT>();
            this.VEN_CONCILIACION_PRODUCTOS = new HashSet<VEN_CONCILIACION_PRODUCTOS>();
            this.VEN_ENTREGA_DT = new HashSet<VEN_ENTREGA_DT>();
            this.VEN_FACTURAS_DAY_DT = new HashSet<VEN_FACTURAS_DAY_DT>();
            this.VEN_FACTURAS_DT = new HashSet<VEN_FACTURAS_DT>();
            this.VEN_ORDENES_DT = new HashSet<VEN_ORDENES_DT>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public string Descripción { get; set; }
        public string Enlace { get; set; }
        public string Clase { get; set; }
        public string GrupoID { get; set; }
        public string ProveedorID { get; set; }
        public string CtaMayorID { get; set; }
        public string CtaVentasID { get; set; }
        public string CtaCostosID { get; set; }
        public string CtaDescuentoID { get; set; }
        public string CtaDevoluciónID { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public string Ubicación { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Modelo { get; set; }
        public string Procedencia { get; set; }
        public Nullable<decimal> StockMáximo { get; set; }
        public Nullable<decimal> StockMínimo { get; set; }
        public string Método { get; set; }
        public string ImpuestoID { get; set; }
        public string Empaque { get; set; }
        public Nullable<decimal> Medida { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> CostoLista { get; set; }
        public Nullable<decimal> CostoCompra { get; set; }
        public Nullable<decimal> CostoRp { get; set; }
        public Nullable<decimal> Precio1 { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Precio4 { get; set; }
        public Nullable<decimal> Precio5 { get; set; }
        public Nullable<decimal> Precio6 { get; set; }
        public Nullable<decimal> Precio7 { get; set; }
        public Nullable<decimal> Promoción { get; set; }
        public Nullable<decimal> Conversión { get; set; }
        public bool Comisión { get; set; }
        public string Formula { get; set; }
        public Nullable<decimal> Comisión1 { get; set; }
        public Nullable<decimal> Comisión2 { get; set; }
        public Nullable<decimal> Comisión3 { get; set; }
        public Nullable<decimal> Comisión4 { get; set; }
        public Nullable<decimal> Comisión5 { get; set; }
        public Nullable<decimal> Comisión6 { get; set; }
        public Nullable<decimal> TasaUtilidadMin { get; set; }
        public Nullable<decimal> TasaUtilidadMax { get; set; }
        public string Foto { get; set; }
        public Nullable<bool> Vendible { get; set; }
        public bool Anulado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> UnidadesProm { get; set; }
        public Nullable<decimal> FactorProm { get; set; }
        public string PromociónID { get; set; }
        public string ImpuestoCompraID { get; set; }
        public Nullable<decimal> BTasaDescuento { get; set; }
        public Nullable<decimal> BTasaFinanciero { get; set; }
        public Nullable<decimal> BTasaEspecial { get; set; }
        public Nullable<decimal> Precio8 { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<decimal> Entrega { get; set; }
        public Nullable<decimal> TasaCrédito { get; set; }
        public string Impuesto4ID { get; set; }
        public Nullable<bool> Balanza { get; set; }
        public Nullable<bool> PorUnidad { get; set; }
        public string PartidaID { get; set; }
        public string Siglas_Proveedor { get; set; }
        public string Código_Original { get; set; }
        public string Código_Fábrica { get; set; }
        public string CtaVentasExtID { get; set; }
        public string CtaDescuentoExtID { get; set; }
        public Nullable<decimal> CostoOld { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> CostoIP { get; set; }
        public Nullable<decimal> CostoMOD { get; set; }
        public string RetenciónFuenteID { get; set; }
        public string RetenciónIvaID { get; set; }
        public string Estación { get; set; }
        public Nullable<bool> Hueso { get; set; }
        public Nullable<decimal> UnidadesPromVen { get; set; }
        public Nullable<decimal> FactorPromVen { get; set; }
        public string PromociónVenID { get; set; }
        public Nullable<decimal> Largo { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public string Material { get; set; }
        public string Piezas { get; set; }
        public string Material1 { get; set; }
        public string Tamaño { get; set; }
        public string Calidad { get; set; }
        public Nullable<decimal> DiasAvisoCadudad { get; set; }
        public Nullable<decimal> Precio9 { get; set; }
        public Nullable<decimal> Precio10 { get; set; }
        public Nullable<bool> DeducibleIR { get; set; }
        public string ImpuestoVerdeID { get; set; }
        public Nullable<bool> IsLote { get; set; }
        public Nullable<bool> ConDecimales { get; set; }
        public string Nota { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Alicuota { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<bool> ConSeries { get; set; }
        public string ComponenteID { get; set; }
        public string EscalaID { get; set; }
        public Nullable<bool> ConTallas { get; set; }
        public string TallaID { get; set; }
        public string FotoLD { get; set; }
        public string Casilla104V { get; set; }
        public Nullable<bool> Historico { get; set; }
        public Nullable<bool> Movil { get; set; }
        public Nullable<System.DateTime> FechaInicioPromo { get; set; }
        public Nullable<System.DateTime> FechaFinalPromo { get; set; }
        public Nullable<decimal> Factor1 { get; set; }
        public Nullable<decimal> Factor2 { get; set; }
        public Nullable<decimal> Factor3 { get; set; }
        public Nullable<decimal> Factor4 { get; set; }
        public string CategoriaID { get; set; }
        public string CodManualID { get; set; }
        public string CodResolucionID { get; set; }
        public string DerivadoID { get; set; }
        public decimal R1 { get; set; }
        public decimal R2 { get; set; }
        public decimal Subsidio { get; set; }
        public System.DateTime FechaInicioD { get; set; }
        public System.DateTime FechaFinalD { get; set; }
        public decimal TasaDescuento { get; set; }
        public string Calificación { get; set; }
        public decimal Puntos { get; set; }
        public string Caracteristicas { get; set; }
        public string Beneficios { get; set; }
        public string FConsumoID { get; set; }
        public string CComercialID { get; set; }
        public string DespachoID { get; set; }
        public string TEntrega { get; set; }
        public string StatusPD { get; set; }
        public string Sucursales { get; set; }
        public decimal CanjeSP { get; set; }
        public decimal PrecioSP { get; set; }
        public bool Publicidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACR_DEBITOS_PRODUCTOS> ACR_DEBITOS_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AST_TAREAS> AST_TAREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_CREDITOS_PRODUCTOS> CLI_CREDITOS_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_FACTURAS_DT> COM_FACTURAS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_LIQUIDACIONES_DT> COM_LIQUIDACIONES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXP_FACTURAS_DT> EXP_FACTURAS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXP_ORDENES_DT> EXP_ORDENES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_LIQUIDACION_DT> IMP_LIQUIDACION_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_PEDIDOS_DT> IMP_PEDIDOS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMP_PREPEDIDOS_DT> IMP_PREPEDIDOS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_COMBOS_COMPONENTES> INV_COMBOS_COMPONENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_CONTEO_DT> INV_CONTEO_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_EGRESOS_PRODUCTOS> INV_EGRESOS_PRODUCTOS { get; set; }
        public virtual INV_GRUPOS INV_GRUPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRECIOS_DT> INV_PRECIOS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLI_COTIZACIONES_DT> CLI_COTIZACIONES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_FACTURAS_LOTE_UBICACIONES> COM_FACTURAS_LOTE_UBICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_FISICO_PRODUCTOS> INV_FISICO_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_INGRESOS_LOTE_UBICACIONES> INV_INGRESOS_LOTE_UBICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_CARDEX_DAY> INV_PRODUCTOS_CARDEX_DAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_CARDEX> INV_PRODUCTOS_CARDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_EXHIBICION> INV_PRODUCTOS_EXHIBICION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_MINIMOS> INV_PRODUCTOS_MINIMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_PRECIOS> INV_PRODUCTOS_PRECIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_PROMOCIONES> INV_PRODUCTOS_PROMOCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS_UBICACIONES> INV_PRODUCTOS_UBICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PROMOCIONES_DT> INV_PROMOCIONES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_TRANSFERENCIAS_DT> INV_TRANSFERENCIAS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRV_EGRESOS_PRODUCTOS> SRV_EGRESOS_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_CONCILIACION_DT> VEN_CONCILIACION_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_CONCILIACION_PRODUCTOS> VEN_CONCILIACION_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_ENTREGA_DT> VEN_ENTREGA_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_FACTURAS_DAY_DT> VEN_FACTURAS_DAY_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_FACTURAS_DT> VEN_FACTURAS_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_ORDENES_DT> VEN_ORDENES_DT { get; set; }
    }
}
