//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_CONVERSIONES_DT
    {
        public string ID { get; set; }
        public string ConversionID { get; set; }
        public string ProductoID { get; set; }
        public string Tipo { get; set; }
        public decimal Cantidad { get; set; }
        public string Empaque { get; set; }
        public decimal Factor { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public decimal Costo { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string DivisaID { get; set; }
        public Nullable<decimal> Cambio { get; set; }
        public string CtaMayorId { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> TasaMP { get; set; }
        public Nullable<decimal> CostoMP { get; set; }
        public Nullable<decimal> CostoIP { get; set; }
        public string BodegaID { get; set; }
    
        public virtual INV_CONVERSIONES INV_CONVERSIONES { get; set; }
    }
}
