//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PRODUCTOS_PRECIOS
    {
        public string ProductoID { get; set; }
        public Nullable<decimal> Rango1 { get; set; }
        public Nullable<decimal> Rango2 { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ID { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public decimal tasaUtilidad { get; set; }
        public bool placa { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
    
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
