//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PRODUCTOS_PRECIOS_HISTORICO
    {
        public string ProductoID { get; set; }
        public decimal Rango1 { get; set; }
        public decimal Rango2 { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ID { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public string DocumentoID { get; set; }
        public string Número { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> AnteriorP1 { get; set; }
        public Nullable<decimal> AnteriorP2 { get; set; }
        public Nullable<decimal> AnteriorP3 { get; set; }
        public Nullable<decimal> ActualP1 { get; set; }
        public Nullable<decimal> ActualP2 { get; set; }
        public Nullable<decimal> ActualP3 { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
