//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_EGRESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_EGRESOS()
        {
            this.INV_EGRESOS_PRODUCTOS = new HashSet<INV_EGRESOS_PRODUCTOS>();
            this.INV_EGRESOS_RUBROS = new HashSet<INV_EGRESOS_RUBROS>();
        }
    
        public string ID { get; set; }
        public string BodegaID { get; set; }
        public string AsientoID { get; set; }
        public string Bodega_Num { get; set; }
        public string Número { get; set; }
        public string OrdenID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public decimal Valor_Base { get; set; }
        public bool Despachado { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string Estado { get; set; }
        public string TransportistaID { get; set; }
        public string MovUniqueId { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public bool impreso { get; set; }
        public string MotivoID { get; set; }
        public bool Aprobado { get; set; }
        public string AprobadoPor { get; set; }
        public System.DateTime AprobadoDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_EGRESOS_PRODUCTOS> INV_EGRESOS_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_EGRESOS_RUBROS> INV_EGRESOS_RUBROS { get; set; }
    }
}
