//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PROMOCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_PROMOCIONES()
        {
            this.INV_PROMOCIONES_DT = new HashSet<INV_PROMOCIONES_DT>();
            this.INV_PROMOCIONES_DT2 = new HashSet<INV_PROMOCIONES_DT2>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Final { get; set; }
        public string HInicio { get; set; }
        public string HFinal { get; set; }
        public string ClaseCliente { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Completen { get; set; }
        public bool IsUnidades { get; set; }
        public Nullable<decimal> Maximo { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string RubroID { get; set; }
        public decimal Medida { get; set; }
        public decimal Modo { get; set; }
        public string GrupoID { get; set; }
        public string Calificacion { get; set; }
        public string GruposCliente { get; set; }
        public bool Todos { get; set; }
        public decimal TasaDescuento { get; set; }
        public string MsjTickets { get; set; }
        public string Sucursales { get; set; }
        public byte[] Foto { get; set; }
        public bool ConSeries { get; set; }
        public string FormaPago { get; set; }
        public bool SoloPDP { get; set; }
        public bool SoloConIva { get; set; }
        public bool SoloSinIva { get; set; }
        public bool VenderXUnd { get; set; }
        public bool IsPrimera { get; set; }
        public string Mensaje1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PROMOCIONES_DT> INV_PROMOCIONES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PROMOCIONES_DT2> INV_PROMOCIONES_DT2 { get; set; }
    }
}
