//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PRODUCTOS_PROMOCIONES
    {
        public string ID { get; set; }
        public string ProductoID { get; set; }
        public string ProductoPromoID { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> UnidadesPromo { get; set; }
        public Nullable<byte> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<System.DateTime> UpdateExportadoDate { get; set; }
        public Nullable<decimal> Replicar { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string TipoCliente { get; set; }
        public Nullable<decimal> Cupo { get; set; }
        public string Sucursal { get; set; }
        public decimal Exportadocandidate { get; set; }
        public string cuentaid { get; set; }
        public bool Adicional { get; set; }
        public decimal Maximo { get; set; }
        public decimal Stock { get; set; }
        public decimal Saldo { get; set; }
        public decimal TasaInv { get; set; }
        public bool AplicaPos { get; set; }
        public string Clase { get; set; }
        public decimal Hasta { get; set; }
    
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
    }
}
