//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GUIAS_REMISION
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string MotivoID { get; set; }
        public string Referencia { get; set; }
        public string FacturaID { get; set; }
        public string NúmeroVenta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public string ClienteID { get; set; }
        public string TransportistaID { get; set; }
        public string Transportista { get; set; }
        public string Vehículo { get; set; }
        public string Color { get; set; }
        public string Placa { get; set; }
        public string Consignado { get; set; }
        public string DirePartida { get; set; }
        public string DireLlegada { get; set; }
        public string Detalle { get; set; }
        public string Nota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string TransporteID { get; set; }
        public string ContenidoID { get; set; }
        public string autorización { get; set; }
        public string SRI_ACK { get; set; }
        public string SRI_DHA { get; set; }
        public string Secuencia { get; set; }
        public string Estado { get; set; }
        public string TRuc { get; set; }
        public bool Interna { get; set; }
    }
}
