//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TRANSFERENCIAS_DT
    {
        public string ID { get; set; }
        public string TransferenciaID { get; set; }
        public string ProductoID { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Empaque { get; set; }
        public decimal Costo { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string OrdenDTID { get; set; }
        public Nullable<decimal> Ingresado { get; set; }
        public Nullable<decimal> Recibido { get; set; }
        public Nullable<decimal> TotalRecibido { get; set; }
        public Nullable<decimal> UnidadesReservar { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
    
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
        public virtual INV_TRANSFERENCIAS INV_TRANSFERENCIAS { get; set; }
    }
}
