//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GRUPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INV_GRUPOS()
        {
            this.INV_PRODUCTOS = new HashSet<INV_PRODUCTOS>();
        }
    
        public string ID { get; set; }
        public string PadreID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Orden { get; set; }
        public string Ruta { get; set; }
        public bool Anulado { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<bool> Surtido { get; set; }
        public string Presupuesto { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> DescMartes { get; set; }
        public Nullable<bool> DescMiércoles { get; set; }
        public Nullable<bool> DescJueves { get; set; }
        public Nullable<bool> DescViernes { get; set; }
        public Nullable<bool> DescSábado { get; set; }
        public Nullable<bool> DescDomingo { get; set; }
        public Nullable<decimal> TasaLunes { get; set; }
        public Nullable<decimal> TasaMartes { get; set; }
        public Nullable<decimal> TasaMiércoles { get; set; }
        public Nullable<decimal> TasaJueves { get; set; }
        public Nullable<decimal> TasaViernes { get; set; }
        public Nullable<decimal> TasaSábado { get; set; }
        public Nullable<decimal> TasaDomingo { get; set; }
        public Nullable<bool> DescLunes { get; set; }
        public bool conPrecioMY { get; set; }
        public Nullable<decimal> TasaTC { get; set; }
        public string horaFinal { get; set; }
        public string horaInicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INV_PRODUCTOS> INV_PRODUCTOS { get; set; }
    }
}
