//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIIF_CODIGOS
    {
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Ruta { get; set; }
        public string Orden { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public string Tipo { get; set; }
        public string PadreID { get; set; }
        public string Clase { get; set; }
        public string Nota { get; set; }
        public string Variable { get; set; }
        public string Fórmula { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public bool SInicial { get; set; }
        public bool Movimiento { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
