//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_DOCUMENTOS
    {
        public string ID { get; set; }
        public string UsuarioID { get; set; }
        public string BuzónID { get; set; }
        public string DeID { get; set; }
        public string ParaID { get; set; }
        public string Tipo { get; set; }
        public string DocumentoID { get; set; }
        public string Asunto { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public bool Revisado { get; set; }
        public string RevisadoPor { get; set; }
        public Nullable<System.DateTime> RevisadoDate { get; set; }
        public string RevisadoNota { get; set; }
        public bool Aprobado { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> AprobadoDate { get; set; }
        public string AprobadoNota { get; set; }
        public bool Negado { get; set; }
        public string NegadoPor { get; set; }
        public Nullable<System.DateTime> NegadoDate { get; set; }
        public string NegadoNota { get; set; }
        public bool Terminado { get; set; }
        public string TerminadoPor { get; set; }
        public Nullable<System.DateTime> TerminadoDate { get; set; }
        public string TerminadoNota { get; set; }
        public bool Transferido { get; set; }
        public string TransferidoPor { get; set; }
        public Nullable<System.DateTime> TransferidoDate { get; set; }
        public string TransferidoNota { get; set; }
        public string Ruta { get; set; }
        public string RTF { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
