//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_CONTACTOS
    {
        public string ID { get; set; }
        public string Tipo { get; set; }
        public string BuzónID { get; set; }
        public string UsuarioID { get; set; }
        public string Categoría { get; set; }
        public string Tratamiento { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Cargo { get; set; }
        public string Empresa { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string ZIP { get; set; }
        public string País { get; set; }
        public string Teléfono1 { get; set; }
        public string Extensión { get; set; }
        public string Fax { get; set; }
        public string Teléfono2 { get; set; }
        public string EMail { get; set; }
        public string WWW { get; set; }
        public string PDirección { get; set; }
        public string PCiudad { get; set; }
        public string PProvincia { get; set; }
        public string PZIP { get; set; }
        public string PPaís { get; set; }
        public string PTeléfono1 { get; set; }
        public string PCelular { get; set; }
        public string PFax { get; set; }
        public string PTeléfono2 { get; set; }
        public string PEMail { get; set; }
        public string PWWW { get; set; }
        public bool Público { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string Nota { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
