//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG_TASK
    {
        public string ID { get; set; }
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public string ClienteID { get; set; }
        public string CategoriaID { get; set; }
        public string Detalle { get; set; }
        public string EmpleadoID { get; set; }
        public string UsuarioID { get; set; }
        public string Problema { get; set; }
        public Nullable<decimal> Prioridad { get; set; }
        public Nullable<decimal> Estado { get; set; }
        public Nullable<decimal> Avance { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public string Horaini { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string HoraFin { get; set; }
        public bool Completado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool IsPrivado { get; set; }
        public string Tiempo { get; set; }
        public decimal Horas { get; set; }
        public decimal Minutos { get; set; }
    }
}
