//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CIERRES_DT
    {
        public string CierreID { get; set; }
        public string FormaPago { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.Guid> IDBZ { get; set; }
    }
}
