//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CIERRES
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string CajaID { get; set; }
        public string UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string Detalle { get; set; }
        public string Nota { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> B100 { get; set; }
        public Nullable<decimal> B50 { get; set; }
        public Nullable<decimal> B20 { get; set; }
        public Nullable<decimal> B10 { get; set; }
        public Nullable<decimal> B5 { get; set; }
        public Nullable<decimal> B1 { get; set; }
        public Nullable<decimal> M100 { get; set; }
        public Nullable<decimal> M50 { get; set; }
        public Nullable<decimal> M25 { get; set; }
        public Nullable<decimal> M10 { get; set; }
        public Nullable<decimal> M5 { get; set; }
        public Nullable<decimal> M1 { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheques { get; set; }
        public Nullable<decimal> Depositos { get; set; }
        public Nullable<decimal> Tarjetas { get; set; }
        public Nullable<decimal> Transferencias { get; set; }
        public Nullable<decimal> Creditos { get; set; }
        public Nullable<decimal> Retenciones { get; set; }
        public Nullable<decimal> Retiros { get; set; }
        public Nullable<decimal> Fondo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalCierre { get; set; }
        public string DivisiónID { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public string EditadoPor { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string PcID { get; set; }
        public Nullable<bool> Impreso { get; set; }
        public Nullable<decimal> CantidadCheques { get; set; }
        public Nullable<decimal> CantidadVouchers { get; set; }
        public Nullable<decimal> TotalCheques { get; set; }
        public Nullable<decimal> TotalVouchers { get; set; }
        public Nullable<decimal> TotalRetenciones { get; set; }
        public Nullable<decimal> TotalBonos { get; set; }
        public Nullable<decimal> TotalCreditos { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public decimal CantidadChequesCredito { get; set; }
        public decimal CantidadCobros { get; set; }
        public decimal cantidadCreditos { get; set; }
        public decimal CobrosCredito { get; set; }
        public decimal CobrosCreditoCheques { get; set; }
        public string MovUniqueId { get; set; }
        public decimal CantidadDomi { get; set; }
        public decimal Domicilio { get; set; }
        public decimal NC { get; set; }
        public decimal CantidadVouchersGift { get; set; }
        public decimal TotalVouchersGift { get; set; }
    }
}
