//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CIERRES_CAJA
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string TirillaID { get; set; }
        public string CajaID { get; set; }
        public string UsuarioID { get; set; }
        public string EmpleadoID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Nota { get; set; }
        public string AsientoID { get; set; }
        public string IngresoID { get; set; }
        public string BodegaID { get; set; }
        public string BovedaID { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<decimal> Facturas { get; set; }
        public Nullable<decimal> Devoluciones { get; set; }
        public Nullable<decimal> Egresos { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheques { get; set; }
        public Nullable<decimal> Depositos { get; set; }
        public Nullable<decimal> Tarjetas { get; set; }
        public Nullable<decimal> Transferencias { get; set; }
        public Nullable<decimal> Creditos { get; set; }
        public Nullable<decimal> RetencionIR { get; set; }
        public Nullable<decimal> RetencionIVA { get; set; }
        public Nullable<decimal> Retiros { get; set; }
        public Nullable<decimal> Sobrante { get; set; }
        public Nullable<decimal> Faltante { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> TotalCierre { get; set; }
        public string DivisiónID { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public string EditadoPor { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string PcID { get; set; }
        public Nullable<bool> Impreso { get; set; }
        public decimal Impuesto { get; set; }
        public decimal SubTotal { get; set; }
        public decimal NC { get; set; }
        public decimal TarjetaGift { get; set; }
    }
}
