//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_FACTURAS
    {
        public string ID { get; set; }
        public string ClienteID { get; set; }
        public string Detalle { get; set; }
        public string Ruc { get; set; }
        public string VendedorID { get; set; }
        public string EmpleadoID { get; set; }
        public string TérminoID { get; set; }
        public string IngresoID { get; set; }
        public string DivisiónID { get; set; }
        public string CajaID { get; set; }
        public bool Contado { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public bool Cerrada { get; set; }
        public bool Remunerada { get; set; }
        public bool Remunerar { get; set; }
        public Nullable<decimal> Comisión { get; set; }
        public string Comisión_Nota { get; set; }
        public string RolID { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Crédito { get; set; }
        public string NoCheque { get; set; }
        public string Banco { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public string NoCuenta { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public string Nombre_tarjeta { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string NoTarjeta { get; set; }
        public string Propietario { get; set; }
        public string Autorización { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string Tipo_ComprobanteID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
