//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_ORDENES
    {
        public string Id { get; set; }
        public string EmpleadoID { get; set; }
        public string ProductoID { get; set; }
        public decimal Cantidad { get; set; }
        public string Detalle { get; set; }
        public string DivisiónID { get; set; }
        public string Lote { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Vencimiento { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public string Estado { get; set; }
        public bool Negado { get; set; }
        public bool Aprobado { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> AprobadoDate { get; set; }
        public string AprobadoNota { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Requerido { get; set; }
        public string RequeridoPor { get; set; }
        public Nullable<System.DateTime> RequeridoDate { get; set; }
        public bool Procesado { get; set; }
        public string ProcesadoPor { get; set; }
        public Nullable<System.DateTime> ProcesadoDate { get; set; }
        public string LiquidaciónID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ClienteID { get; set; }
    }
}
