//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRV_INGRESOS_PRODUCTOS
    {
        public string IngresoID { get; set; }
        public string ProductoID { get; set; }
        public string OrdenDTID { get; set; }
        public string BodegaID { get; set; }
        public decimal Cantidad { get; set; }
        public string Empaque { get; set; }
        public decimal Costo { get; set; }
        public decimal Factor { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string CtaMayorID { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
