//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRV_PRODUCTOS
    {
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public string Clase { get; set; }
        public string GrupoID { get; set; }
        public string ProveedorID { get; set; }
        public string CtaMayorID { get; set; }
        public string CtaGastosID { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Modelo { get; set; }
        public string Procedencia { get; set; }
        public Nullable<decimal> StockMáximo { get; set; }
        public Nullable<decimal> StockMínimo { get; set; }
        public Nullable<decimal> TasaRev { get; set; }
        public string Método { get; set; }
        public string ImpuestoID { get; set; }
        public string Empaque { get; set; }
        public Nullable<decimal> MedidaVolumen { get; set; }
        public Nullable<decimal> MedidaLongitud { get; set; }
        public Nullable<decimal> MedidaSuperficie { get; set; }
        public Nullable<decimal> MedidaPeso { get; set; }
        public Nullable<decimal> MedidaLíquido { get; set; }
        public Nullable<decimal> Medida { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> CostoRP { get; set; }
        public Nullable<decimal> CostoLista { get; set; }
        public Nullable<decimal> CostoCompra { get; set; }
        public string Foto { get; set; }
        public string Ubicación { get; set; }
        public bool Anulado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ImpuestoIceID { get; set; }
        public Nullable<bool> Seguro { get; set; }
        public Nullable<bool> Flete { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string RetenciónFuenteID { get; set; }
        public string RetenciónIvaID { get; set; }
    }
}
