//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRV_FACTURAS_GASTOS_MOVIL
    {
        public int ID { get; set; }
        public bool Fisica { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public string SerieFactura { get; set; }
        public string NumeroFactura { get; set; }
        public string Ruc { get; set; }
        public string NombreProveedor { get; set; }
        public string AutorizacionFactura { get; set; }
        public string UsuarioId { get; set; }
        public string GastoId { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoDate { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Aprobado { get; set; }
        public string AprobadoPor { get; set; }
        public bool Anulado { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public Nullable<decimal> Subtotal12 { get; set; }
        public Nullable<decimal> Subtotal0 { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public bool procesado { get; set; }
        public string Tipo { get; set; }
    }
}
