//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRV_FACTURAS
    {
        public string ID { get; set; }
        public string ProveedorID { get; set; }
        public string AsientoID { get; set; }
        public string TérminoID { get; set; }
        public string DivisiónID { get; set; }
        public string OrdenID { get; set; }
        public string Detalle { get; set; }
        public string Número { get; set; }
        public string Tipo { get; set; }
        public string Referencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Recibido { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public bool Retenido { get; set; }
        public string acrAutorizacion { get; set; }
        public Nullable<System.DateTime> Fecha_documento { get; set; }
        public string acrSerie { get; set; }
        public string acrSecuencia { get; set; }
        public string Credito_tributarioID { get; set; }
        public string Tipo_comprobanteID { get; set; }
        public Nullable<decimal> Varios { get; set; }
        public Nullable<bool> Procesado_sri { get; set; }
        public Nullable<bool> ArchivoSRI { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<decimal> ImpuestoIce { get; set; }
        public string ImportaciónID { get; set; }
        public string LiquidaciónID { get; set; }
        public string ExportaciónID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string ServTecnicoID { get; set; }
        public string SRI_ACK { get; set; }
        public string OrdenPRDID { get; set; }
        public decimal Compensacion { get; set; }
        public string Estado { get; set; }
        public string SRI_DHA { get; set; }
        public decimal BaseIva { get; set; }
        public decimal BaseCero { get; set; }
        public decimal BaseExc { get; set; }
        public decimal BaseNoObj { get; set; }
        public Nullable<System.DateTime> Editadodate { get; set; }
        public string TipoGastoID { get; set; }
        public decimal BaseCons { get; set; }
    }
}
