//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMA_PRODUCTOS_SERIES
    {
        public string ProductoID { get; set; }
        public string Serie { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaIng { get; set; }
        public Nullable<System.DateTime> FechaEgr { get; set; }
        public Nullable<System.DateTime> Exportadodate { get; set; }
        public string SucursalID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string BodegaID { get; set; }
        public System.DateTime CreadoDate { get; set; }
    }
}
