//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMA_PRODUCTOS
    {
        public string Serie { get; set; }
        public string ProductoID { get; set; }
        public string FacturaID { get; set; }
        public string CompraID { get; set; }
        public string ImportaciónID { get; set; }
        public string IngresoID { get; set; }
        public string EgresoID { get; set; }
        public string EnsamblajeID { get; set; }
        public string ClienteID { get; set; }
        public string ProveedorID { get; set; }
        public string IngImportaciónID { get; set; }
        public string IngCompraID { get; set; }
        public string IngVentaID { get; set; }
        public string IngEnsamblajeID { get; set; }
        public string CLIngresoID { get; set; }
        public string PDIngresoID { get; set; }
        public string PVIngresoID { get; set; }
        public string CLEgresoID { get; set; }
        public string PDEgresoID { get; set; }
        public string PVEgresoID { get; set; }
        public Nullable<System.DateTime> GarantíaVenta { get; set; }
        public Nullable<System.DateTime> GarantíaCompra { get; set; }
        public Nullable<System.DateTime> GarantíaImportación { get; set; }
        public Nullable<System.DateTime> FechaIngRMA { get; set; }
        public Nullable<System.DateTime> FechaEgrRMA { get; set; }
        public string ProductoIngID { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaRetorno { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> CostoRMA { get; set; }
        public Nullable<decimal> CostoVTA { get; set; }
        public Nullable<decimal> PrecioVTA { get; set; }
        public string Problema { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    }
}
