//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEG_GRUPOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEG_GRUPOS()
        {
            this.SEG_GRUPOS1 = new HashSet<SEG_GRUPOS>();
            this.SEG_USUARIOS = new HashSet<SEG_USUARIOS>();
        }
    
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string PadreID { get; set; }
        public bool Anulado { get; set; }
        public string Ruta { get; set; }
        public string Orden { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string CreadoPor { get; set; }
        public string EditadoPor { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_GRUPOS> SEG_GRUPOS1 { get; set; }
        public virtual SEG_GRUPOS SEG_GRUPOS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEG_USUARIOS> SEG_USUARIOS { get; set; }
    }
}
