//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_INTERFASE_VENTAS
    {
        public string ID { get; set; }
        public string Número { get; set; }
        public string Turno { get; set; }
        public string CajaEfectivoID { get; set; }
        public string CajaTarjetaID { get; set; }
        public string BodegaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string HoraInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string HoraFinal { get; set; }
        public string Data_Base { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> SubtotalSinIva { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> TotalGeneral { get; set; }
        public Nullable<decimal> TotalEfectivo { get; set; }
        public Nullable<decimal> TotalCredito { get; set; }
        public Nullable<decimal> TotalTarjeta { get; set; }
        public Nullable<decimal> TotalRegistros { get; set; }
        public Nullable<decimal> TotalTransacciones { get; set; }
        public string Nota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public bool Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public bool ExportadoUpdate { get; set; }
    }
}
