//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_SUCURSALES
    {
        public string ID { get; set; }
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string Dirección { get; set; }
        public string Teléfonos { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string Establecimiento { get; set; }
        public bool PrintTitle { get; set; }
        public string PrecioID { get; set; }
        public string FormatoID { get; set; }
        public string RegionID { get; set; }
        public string DespachoID { get; set; }
        public string CiudadID { get; set; }
        public string SupervisorID { get; set; }
        public string GerenteID { get; set; }
        public string ClusterID { get; set; }
        public bool ControlaStock { get; set; }
    }
}
