//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIS_ERRORLOG_FE
    {
        public int ID { get; set; }
        public string Documento { get; set; }
        public string Modulo { get; set; }
        public string DocumentoID { get; set; }
        public string Numero { get; set; }
        public string Mensaje { get; set; }
        public string CreadoPor { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
    }
}
