//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRI_RANGOS_SECUENCIAS
    {
        public string RangoID { get; set; }
        public string Código { get; set; }
        public string Serie { get; set; }
        public string Establecimiento { get; set; }
        public string Documento { get; set; }
        public Nullable<decimal> Inicio { get; set; }
        public Nullable<decimal> Fin { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string TipoComprobanteID { get; set; }
        public string CódigoDoc { get; set; }
        public Nullable<decimal> FinOld { get; set; }
        public string PC_CAJA { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string HostNameID { get; set; }
        public Nullable<bool> anulado { get; set; }
        public string id { get; set; }
        public string punto { get; set; }
        public string editadopor { get; set; }
        public Nullable<System.DateTime> editadodate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
