//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRI_DOCUMENTOS_RECIBIDOS
    {
        public string PersonaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Tipo { get; set; }
        public string Ruc { get; set; }
        public string Detalle { get; set; }
        public string Secuencia { get; set; }
        public string SRI_ACK { get; set; }
        public string SRI_AUT { get; set; }
        public string SRI_DHA { get; set; }
        public string DocumentoNum { get; set; }
        public string Estado { get; set; }
        public decimal Total { get; set; }
        public decimal Valor1 { get; set; }
        public decimal Valor2 { get; set; }
        public decimal Valor3 { get; set; }
        public decimal Valor4 { get; set; }
        public decimal Valor5 { get; set; }
        public System.DateTime CreadoDate { get; set; }
        public bool Exportado { get; set; }
        public bool ExportadoUpdate { get; set; }
    }
}
