//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRI_RANGOS
    {
        public string ID { get; set; }
        public string Código { get; set; }
        public string Autorización { get; set; }
        public string TipoTramiteID { get; set; }
        public string Nota { get; set; }
        public Nullable<System.DateTime> Emision { get; set; }
        public Nullable<System.DateTime> Validez { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string CreadoPor { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public string AutorizaciónOLD { get; set; }
        public Nullable<bool> Vigente { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
    }
}
