//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_EGRESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRV_EGRESOS()
        {
            this.SRV_EGRESOS_PRODUCTOS = new HashSet<SRV_EGRESOS_PRODUCTOS>();
        }
    
        public string ID { get; set; }
        public string BodegaID { get; set; }
        public string AsientoID { get; set; }
        public string Número { get; set; }
        public string OrdenID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public decimal Valor_Base { get; set; }
        public string Nota { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string DivisiónID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRV_EGRESOS_PRODUCTOS> SRV_EGRESOS_PRODUCTOS { get; set; }
    }
}
