//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRV_ORDENES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SRV_ORDENES()
        {
            this.SRV_ORDENES_TIPOS = new HashSet<SRV_ORDENES_TIPOS>();
            this.SRV_ORDENES_DT = new HashSet<SRV_ORDENES_DT>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string Detalle { get; set; }
        public string ClienteID { get; set; }
        public string FacturaID { get; set; }
        public string EtapaID { get; set; }
        public string TecnicoID { get; set; }
        public string ProductoID { get; set; }
        public string NoSerie { get; set; }
        public string Desc_Problema { get; set; }
        public string Observación { get; set; }
        public Nullable<decimal> Valor_APagar { get; set; }
        public bool Garantía { get; set; }
        public bool Terminado { get; set; }
        public string EtapaAnteriorID { get; set; }
        public string DivisiónID { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string SucursalID { get; set; }
        public string pcID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public string ProductoName { get; set; }
        public string MarcaID { get; set; }
        public string Modelo { get; set; }
        public string Accesorios { get; set; }
        public Nullable<bool> Facturado { get; set; }
        public Nullable<decimal> Dias { get; set; }
        public string foto { get; set; }
        public Nullable<bool> IsImportación { get; set; }
        public decimal Exportadocandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRV_ORDENES_TIPOS> SRV_ORDENES_TIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SRV_ORDENES_DT> SRV_ORDENES_DT { get; set; }
    }
}
