//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_FACTURASREM_DT
    {
        public string ID { get; set; }
        public string FacturaID { get; set; }
        public string Tip_Identificacion { get; set; }
        public string Cedula { get; set; }
        public string Serie { get; set; }
        public string Secuencia { get; set; }
        public string Autorizacion { get; set; }
        public string Validez { get; set; }
        public string CreditoTributarioID { get; set; }
        public string ComprobanteID { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Impuesto_Name { get; set; }
        public string Detalle { get; set; }
        public string ImpuestoID { get; set; }
        public string CuentaID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PCID { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> SubtotalCero { get; set; }
        public Nullable<decimal> SubtotalDoce { get; set; }
        public decimal Compensacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
