//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_ORDENES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEN_ORDENES()
        {
            this.VEN_CONCILIACION_ORDENES = new HashSet<VEN_CONCILIACION_ORDENES>();
            this.VEN_ORDENES_DT = new HashSet<VEN_ORDENES_DT>();
        }
    
        public string ID { get; set; }
        public string ClienteID { get; set; }
        public string Detalle { get; set; }
        public string VendedorID { get; set; }
        public string TérminoID { get; set; }
        public string DivisiónID { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Entregado { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Nota { get; set; }
        public string Nota2 { get; set; }
        public string Estado { get; set; }
        public bool Negado { get; set; }
        public bool Aprobado { get; set; }
        public string AprobadoPor { get; set; }
        public Nullable<System.DateTime> AprobadoDate { get; set; }
        public string AprobadoNota { get; set; }
        public bool Egresado { get; set; }
        public bool Facturado { get; set; }
        public string FacturadoPor { get; set; }
        public Nullable<System.DateTime> FacturadoDate { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string AsientoID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public string CréditoPor { get; set; }
        public string CréditoNota { get; set; }
        public Nullable<System.DateTime> CréditoDate { get; set; }
        public Nullable<bool> Movil { get; set; }
        public Nullable<bool> Consolidado { get; set; }
        public Nullable<bool> Despachado { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<bool> Envio { get; set; }
        public bool Impreso { get; set; }
        public decimal DescuentoEspecial { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string EmpresariaID { get; set; }
    
        public virtual SIS_DIVISIONES SIS_DIVISIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_CONCILIACION_ORDENES> VEN_CONCILIACION_ORDENES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_ORDENES_DT> VEN_ORDENES_DT { get; set; }
    }
}
