//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_CONCILIACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEN_CONCILIACION()
        {
            this.VEN_CONCILIACION_DT = new HashSet<VEN_CONCILIACION_DT>();
            this.VEN_CONCILIACION_PRODUCTOS = new HashSet<VEN_CONCILIACION_PRODUCTOS>();
            this.VEN_CONCILIACION_ORDENES = new HashSet<VEN_CONCILIACION_ORDENES>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public string DivisiónID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string BodegaID_Origen1 { get; set; }
        public string BodegaID_Origen2 { get; set; }
        public string BodegaID_Destino { get; set; }
        public string TransferenciaOrigenID1 { get; set; }
        public string TransferenciaOrigenID2 { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public bool Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> UpdateExportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_CONCILIACION_DT> VEN_CONCILIACION_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_CONCILIACION_PRODUCTOS> VEN_CONCILIACION_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_CONCILIACION_ORDENES> VEN_CONCILIACION_ORDENES { get; set; }
    }
}
