//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_FACTURAS_DAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEN_FACTURAS_DAY()
        {
            this.VEN_FACTURAS_DAY_DT = new HashSet<VEN_FACTURAS_DAY_DT>();
        }
    
        public string ID { get; set; }
        public string OrdenID { get; set; }
        public string ClienteID { get; set; }
        public string Detalle { get; set; }
        public string Ruc { get; set; }
        public string AsientoID { get; set; }
        public string VendedorID { get; set; }
        public string EmpleadoID { get; set; }
        public string TérminoID { get; set; }
        public string IngresoID { get; set; }
        public string DivisiónID { get; set; }
        public string CajaID { get; set; }
        public string Secuencia { get; set; }
        public string BodegaID { get; set; }
        public string Bodega_Num { get; set; }
        public bool Contado { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Entregado { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Transporte { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public Nullable<decimal> Crédito { get; set; }
        public string Banco { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public string NoCuenta { get; set; }
        public string NoCheque { get; set; }
        public string Nombre_Tarjeta { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string NoTarjeta { get; set; }
        public string Autorización { get; set; }
        public string Nota { get; set; }
        public string Nota2 { get; set; }
        public bool Croquis { get; set; }
        public bool Cerrada { get; set; }
        public bool Remunerada { get; set; }
        public bool Remunerar { get; set; }
        public Nullable<decimal> Comisión { get; set; }
        public string Comisión_Nota { get; set; }
        public string Número_Guía { get; set; }
        public string Número_OC { get; set; }
        public Nullable<System.DateTime> Fecha_OC { get; set; }
        public string Fact_Preimpresa { get; set; }
        public string RolID { get; set; }
        public Nullable<decimal> Holgura { get; set; }
        public string TipoFactura { get; set; }
        public bool Despachado { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public bool Retenido { get; set; }
        public Nullable<bool> Procesado_sri { get; set; }
        public string RetencionIvaServiciosID { get; set; }
        public string RetencionID { get; set; }
        public string RetencionIvaBienesID { get; set; }
        public string RetencionFuenteID { get; set; }
        public string RetenciónID { get; set; }
        public Nullable<bool> ProcesadoAnulado_SRI { get; set; }
        public string AutorizaciónFA { get; set; }
        public string Validez { get; set; }
        public Nullable<bool> NoControlaStock { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> Impresa { get; set; }
        public Nullable<decimal> TasaComisión { get; set; }
        public Nullable<decimal> Servicio { get; set; }
        public string NoRetención { get; set; }
        public Nullable<decimal> RetenciónIR { get; set; }
        public Nullable<decimal> RetenciónIVA { get; set; }
        public string ContratoID { get; set; }
        public string Estado { get; set; }
        public bool AutoConsumo { get; set; }
        public string CódigoAnexo { get; set; }
        public string SRI_ACK { get; set; }
        public decimal BaseIva { get; set; }
        public decimal BaseCero { get; set; }
        public System.DateTime SRI_DHA { get; set; }
        public string Autorización2 { get; set; }
        public string Nombre_Tarjeta2 { get; set; }
        public string NoTarjeta2 { get; set; }
        public Nullable<decimal> Tarjeta2 { get; set; }
        public Nullable<System.DateTime> Vence2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_FACTURAS_DAY_DT> VEN_FACTURAS_DAY_DT { get; set; }
    }
}
