//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_CONCILIACION_ORDENES
    {
        public string ID { get; set; }
        public string ConciliacionID { get; set; }
        public string OrdenID { get; set; }
        public string BodegaID { get; set; }
        public bool Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public Nullable<decimal> UpdateExportado { get; set; }
        public Nullable<decimal> Replicar { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public decimal Exportadocandidate { get; set; }
    
        public virtual VEN_CONCILIACION VEN_CONCILIACION { get; set; }
        public virtual VEN_ORDENES VEN_ORDENES { get; set; }
    }
}
