//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_ENTREGAS_DT
    {
        public string ID { get; set; }
        public string EntregaID { get; set; }
        public string DetalleID { get; set; }
        public string ProductoID { get; set; }
        public string BodegaID { get; set; }
        public decimal TotalOrder { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<decimal> Despachado { get; set; }
        public string Empaque { get; set; }
        public decimal Factor { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    
        public virtual VEN_ENTREGAS VEN_ENTREGAS { get; set; }
    }
}
