//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_ENTREGAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEN_ENTREGAS()
        {
            this.VEN_DESPACHOS = new HashSet<VEN_DESPACHOS>();
            this.VEN_ENTREGAS_DT = new HashSet<VEN_ENTREGAS_DT>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public string Detalle { get; set; }
        public string DivisiónID { get; set; }
        public string TipoDocumento { get; set; }
        public string DocumentoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string ClienteID { get; set; }
        public string Tipo { get; set; }
        public string Transporte { get; set; }
        public string Nota { get; set; }
        public string Estado { get; set; }
        public bool Despachado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_DESPACHOS> VEN_DESPACHOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_ENTREGAS_DT> VEN_ENTREGAS_DT { get; set; }
    }
}
