//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_ENTREGA_DT
    {
        public string ID { get; set; }
        public string EntregaID { get; set; }
        public string ProductoID { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Facturado { get; set; }
        public decimal Egresado { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> TasaDescuento { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> TasaImpuesto { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public decimal Total { get; set; }
        public string Clase { get; set; }
        public string Detalle_Ex { get; set; }
        public string Empaque { get; set; }
        public string PrecioName { get; set; }
        public decimal Factor { get; set; }
        public Nullable<decimal> SaldoAcum { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public bool Exportado { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public Nullable<decimal> EgresoGuia { get; set; }
        public Nullable<decimal> Unidades { get; set; }
        public Nullable<decimal> Largo { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public string Colores { get; set; }
        public string BodegaID { get; set; }
    
        public virtual INV_PRODUCTOS INV_PRODUCTOS { get; set; }
        public virtual VEN_ENTREGA VEN_ENTREGA { get; set; }
    }
}
