//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_DEVOLUCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEN_DEVOLUCIONES()
        {
            this.VEN_DEVOLUCIONES_DT = new HashSet<VEN_DEVOLUCIONES_DT>();
        }
    
        public string ID { get; set; }
        public string Número { get; set; }
        public string ClienteID { get; set; }
        public string Detalle { get; set; }
        public string AsientoID { get; set; }
        public string IngresoID { get; set; }
        public string DivisiónID { get; set; }
        public string CajaID { get; set; }
        public string FacturaID { get; set; }
        public string VendedorID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public bool Contado { get; set; }
        public bool Cerrada { get; set; }
        public string Nota { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public bool Anulado { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string AnuladoNota { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public string SecuenciaDoc { get; set; }
        public Nullable<bool> Procesado_SRI { get; set; }
        public string Autorización { get; set; }
        public string Secuencia { get; set; }
        public Nullable<bool> NoControlaStock { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> ReImpreso { get; set; }
        public string MotivoID { get; set; }
        public string SRI_ACK { get; set; }
        public Nullable<System.DateTime> SRI_DHA { get; set; }
        public decimal Compensacion { get; set; }
        public decimal Ice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_DEVOLUCIONES_DT> VEN_DEVOLUCIONES_DT { get; set; }
    }
}
