//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEN_FACTURAS()
        {
            this.VEN_DEVOLUCIONES_DT = new HashSet<VEN_DEVOLUCIONES_DT>();
            this.VEN_FACTURAS_DT = new HashSet<VEN_FACTURAS_DT>();
        }
    
        public string ID { get; set; }
        public string OrdenID { get; set; }
        public string ClienteID { get; set; }
        public string Detalle { get; set; }
        public string Ruc { get; set; }
        public string AsientoID { get; set; }
        public string VendedorID { get; set; }
        public string EmpleadoID { get; set; }
        public string TérminoID { get; set; }
        public string IngresoID { get; set; }
        public string DivisiónID { get; set; }
        public string CajaID { get; set; }
        public string Secuencia { get; set; }
        public string BodegaID { get; set; }
        public string Bodega_Num { get; set; }
        public bool Contado { get; set; }
        public string Número { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Entregado { get; set; }
        public string Tipo { get; set; }
        public string DivisaID { get; set; }
        public decimal Cambio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Financiero { get; set; }
        public Nullable<decimal> Impuesto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Transporte { get; set; }
        public Nullable<decimal> Efectivo { get; set; }
        public Nullable<decimal> Cheque { get; set; }
        public Nullable<decimal> Tarjeta { get; set; }
        public Nullable<decimal> Crédito { get; set; }
        public string Banco { get; set; }
        public Nullable<System.DateTime> Fecha_Cheque { get; set; }
        public string NoCuenta { get; set; }
        public string NoCheque { get; set; }
        public string Nombre_Tarjeta { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string NoTarjeta { get; set; }
        public string Autorización { get; set; }
        public string Nota { get; set; }
        public string Nota2 { get; set; }
        public bool Croquis { get; set; }
        public bool Cerrada { get; set; }
        public bool Remunerada { get; set; }
        public bool Remunerar { get; set; }
        public Nullable<decimal> Comisión { get; set; }
        public string Comisión_Nota { get; set; }
        public string Número_Guía { get; set; }
        public string Número_OC { get; set; }
        public Nullable<System.DateTime> Fecha_OC { get; set; }
        public string Fact_Preimpresa { get; set; }
        public string RolID { get; set; }
        public Nullable<decimal> Holgura { get; set; }
        public string TipoFactura { get; set; }
        public bool Despachado { get; set; }
        public bool Anulado { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoDate { get; set; }
        public string AnuladoNota { get; set; }
        public string AnuladoPor { get; set; }
        public Nullable<System.DateTime> AnuladoDate { get; set; }
        public string EditadoPor { get; set; }
        public Nullable<System.DateTime> EditadoDate { get; set; }
        public Nullable<System.DateTime> ExportadoDate { get; set; }
        public string SucursalID { get; set; }
        public string PcID { get; set; }
        public bool Retenido { get; set; }
        public Nullable<bool> Procesado_sri { get; set; }
        public string RetencionIvaServiciosID { get; set; }
        public string RetencionID { get; set; }
        public string RetencionIvaBienesID { get; set; }
        public string RetencionFuenteID { get; set; }
        public string RetenciónID { get; set; }
        public Nullable<bool> ProcesadoAnulado_SRI { get; set; }
        public string AutorizaciónFA { get; set; }
        public string Validez { get; set; }
        public Nullable<bool> NoControlaStock { get; set; }
        public string ExportadoPor { get; set; }
        public Nullable<decimal> Exportado { get; set; }
        public Nullable<decimal> ExportadoUpdate { get; set; }
        public Nullable<decimal> ExportadoCandidate { get; set; }
        public Nullable<bool> Impresa { get; set; }
        public Nullable<decimal> TasaComisión { get; set; }
        public Nullable<decimal> Servicio { get; set; }
        public string NoRetención { get; set; }
        public Nullable<decimal> RetenciónIR { get; set; }
        public Nullable<decimal> RetenciónIVA { get; set; }
        public string ContratoID { get; set; }
        public string CódigoAnexo { get; set; }
        public Nullable<bool> AutoConsumo { get; set; }
        public string Estado { get; set; }
        public string SRI_ACK { get; set; }
        public Nullable<decimal> BaseIva { get; set; }
        public Nullable<decimal> BaseCero { get; set; }
        public string SRI_DHA { get; set; }
        public decimal Tarjeta2 { get; set; }
        public string Nombre_Tarjeta2 { get; set; }
        public System.DateTime Vence2 { get; set; }
        public string NoTarjeta2 { get; set; }
        public string Autorización2 { get; set; }
        public decimal Compensacion { get; set; }
        public Nullable<bool> IsReembolso { get; set; }
        public bool ConTarjeta { get; set; }
        public Nullable<double> Latitud { get; set; }
        public string ListaPrecio { get; set; }
        public Nullable<double> Longitud { get; set; }
        public bool Movil { get; set; }
        public string MovUniqueId { get; set; }
        public string NoAceptacion { get; set; }
        public bool PagoCredito { get; set; }
        public string Responsable { get; set; }
        public decimal Saldo { get; set; }
        public decimal Ice { get; set; }
        public bool Aprobado { get; set; }
        public decimal Financiamiento { get; set; }
        public bool domicilio { get; set; }
        public string CodeTrasporte { get; set; }
        public string Dirección { get; set; }
        public System.DateTime FechaDesp { get; set; }
        public decimal NC { get; set; }
        public string CreditoID { get; set; }
        public decimal Deposito { get; set; }
        public System.DateTime FechaRet { get; set; }
        public decimal Devuelto { get; set; }
        public string Nombre_TarjetaRegalo { get; set; }
        public System.DateTime Vence3 { get; set; }
        public string NoTarjeta3 { get; set; }
        public decimal Tarjeta3 { get; set; }
        public string EmpresariaID { get; set; }
        public decimal PuntosUsados { get; set; }
        public decimal BaseCons { get; set; }
        public string Cupon { get; set; }
        public decimal PuntosGanados { get; set; }
        public Nullable<bool> NCgit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_DEVOLUCIONES_DT> VEN_DEVOLUCIONES_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEN_FACTURAS_DT> VEN_FACTURAS_DT { get; set; }
    }
}
