//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USWsLibrary.ModelDobraDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEN_OPCIONES
    {
        public string ID { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string POS_CAJA_ID { get; set; }
        public string POS_CAJERO_ID { get; set; }
        public string POS_SUPERVISOR_ID { get; set; }
        public string POS_SERIE_FACTURA { get; set; }
        public string POS_SECUENCIA_NVENTA { get; set; }
        public string POS_BLUETOOTH_MAC { get; set; }
        public string POS_DIRECCION_FISICA_BLUETOOTH { get; set; }
        public Nullable<int> POS_CANTIDAD_CARACTERES { get; set; }
        public string POS_SUCURSALID { get; set; }
        public Nullable<bool> POS_CONTROLAR_STOCK { get; set; }
        public Nullable<bool> POS_PRINT_AUTOMATIC { get; set; }
        public Nullable<bool> POS_ADD_PRODUCTS { get; set; }
        public Nullable<bool> POS_PRINT_BLUETOOTH { get; set; }
        public Nullable<bool> POS_PRINT_WIRELESS { get; set; }
        public Nullable<bool> POS_IMPRIME_COPIA { get; set; }
        public string IPSERVER_WIRELESS { get; set; }
        public Nullable<int> PORTSERVER_WIRELESS { get; set; }
        public Nullable<bool> POS_PRINT_TMU220D { get; set; }
        public string POS_EPSON_MAC { get; set; }
        public string CREADOPOR { get; set; }
        public Nullable<System.DateTime> CREADODATE { get; set; }
        public string EDITADOPOR { get; set; }
        public Nullable<System.DateTime> EDITADODATE { get; set; }
        public string PCID { get; set; }
        public bool ANULADO { get; set; }
        public string ANULADOPOR { get; set; }
        public Nullable<System.DateTime> ANULADODATE { get; set; }
        public string EXPORTADOPOR { get; set; }
        public Nullable<System.DateTime> EXPORTADODATE { get; set; }
        public Nullable<decimal> EXPORTADO { get; set; }
        public Nullable<decimal> EXPORTADOUPDATE { get; set; }
        public Nullable<decimal> EXPORTADOCANDIDATE { get; set; }
        public string POS_TIPO_DOCUMENTO { get; set; }
        public Nullable<int> POS_MAX_ITEMS { get; set; }
        public Nullable<decimal> POS_MAX_DINERO_CAJA { get; set; }
        public string POS_BODEGA_ID { get; set; }
        public string POS_Secuencia_Devolucion { get; set; }
    
        public virtual BAN_BANCOS BAN_BANCOS { get; set; }
        public virtual EMP_EMPLEADOS EMP_EMPLEADOS { get; set; }
    }
}
