using System.Collections.Generic;
using USWsLibrary.ModelDobraDatabase;

namespace USWsSync.Core.Registry
{
    public static class TableRegistry
    {
        public static IReadOnlyList<TableSyncDefinition> DownloadTables { get; } = new List<TableSyncDefinition>
        {
            TableSyncDefinition.Create<SIS_PARAMETROS>("SIS_PARAMETROS", "listSisParametros", "saveSisParametros"),
            TableSyncDefinition.Create<CLI_CLIENTES>("CLI_CLIENTES", "listClient", "saveCliente"),
            TableSyncDefinition.Create<INV_PRODUCTOS>("INV_PRODUCTOS", "listProducts", "saveProducto"),
            TableSyncDefinition.Create<INV_PRODUCTOS_EMPAQUES>("INV_PRODUCTOS_EMPAQUES", "listPackagesProducts", "savePackageProductos"),
            TableSyncDefinition.Create<INV_PRODUCTOS_PRECIOS>("INV_PRODUCTOS_PRECIOS", "listPriceProducts", "savePriceProducts"),
            TableSyncDefinition.Create<INV_COMBOS>("INV_COMBOS", "listComboProducts", "saveCombos"),
            TableSyncDefinition.Create<INV_COMBOS_COMPONENTES>("INV_COMBOS_COMPONENTES", "listComboComponentesProducts", "saveComboComponente"),
            TableSyncDefinition.Create<INV_PRECIOS>("INV_PRECIOS", "listInvPrecios", "saveInvPrecio"),
            TableSyncDefinition.Create<INV_PRECIOS_DT>("INV_PRECIOS_DT", "listInvPreciosDt", "saveInvPrecioDt"),
            TableSyncDefinition.Create<INV_RUBROS>("INV_RUBROS", "listInvRubros", "saveInvRubros"),
            TableSyncDefinition.Create<ACC_CUENTAS>("ACC_CUENTAS", "listAccCuentas", "saveAccCuentas"),
            TableSyncDefinition.Create<INV_TRANSFERENCIAS>("INV_TRANSFERENCIAS", "listInvTransferencias", "saveInvTransferencias"),
            TableSyncDefinition.Create<INV_TRANSFERENCIAS_DT>("INV_TRANSFERENCIAS_DT", "listInvTransferenciasDt", "saveInvTransferenciasDt"),
            TableSyncDefinition.Create<EMP_EMPLEADOS>("EMP_EMPLEADOS", "listEmployess", "saveEmployees"),
            TableSyncDefinition.Create<BAN_BANCOS>("BAN_BANCOS", "listBancos", "saveBancos"),
            TableSyncDefinition.Create<CLI_RUBROS>("CLI_RUBROS", "listCliRubros", "saveCliRubros"),
            TableSyncDefinition.Create<INV_EMPAQUES>("INV_EMPAQUES", "listInvPackages", "saveInvPackages"),
            TableSyncDefinition.Create<SEG_PERFILES>("SEG_PERFILES", "listSegProfiles", "saveSegProfiles"),
            TableSyncDefinition.Create<SEG_RECURSOS>("SEG_RECURSOS", "listSegRecursos", "saveSegRecursos"),
            TableSyncDefinition.Create<SEG_USUARIOS>("SEG_USUARIOS", "listSegUsuarios", "saveSegUsuarios"),
            TableSyncDefinition.Create<SIS_DIVISIONES>("SIS_DIVISIONES", "listSisDivisiones", "saveDivisiones"),
            TableSyncDefinition.Create<SIS_SUCURSALES>("SIS_SUCURSALES", "listSisSucursales", "saveSisSucursales"),
            TableSyncDefinition.Create<SRI_SECUENCIAL>("SRI_SECUENCIAL", "listSriSecuencial", "saveSriSecuencial"),
            TableSyncDefinition.Create<CLI_CLIENTES_DEUDAS>("CLI_CLIENTES_DEUDAS", "listClientesDeduas", "saveClienteDeudas"),
            TableSyncDefinition.Create<SEG_PERFILES_RECURSOS>("SEG_PERFILES_RECURSOS", "listSegPerfilesRecursos", "saveSegPerfilesRecursos"),
            TableSyncDefinition.Create<ORG_BUZONES>("ORG_BUZONES", "listOrgBuzones", "saveOrgBuzones"),
            TableSyncDefinition.Create<ORG_DOCUMENTOS>("ORG_DOCUMENTOS", "listOrgDocumentos", "saveOrgDocumentos"),
            TableSyncDefinition.Create<ORG_TAREAS>("ORG_TAREAS", "listOrgTareas", "saveOrgTareas"),
            TableSyncDefinition.Create<SIS_ZONAS>("SIS_ZONAS", "listSisZonas", "saveSisZonas"),
            TableSyncDefinition.Create<INV_PROMOCIONES>("INV_PROMOCIONES", "listInvPromociones", "saveInvPromociones"),
            TableSyncDefinition.Create<INV_PROMOCIONES_DT>("INV_PROMOCIONES_DT", "listInvPromocionesDt", "saveInvPromocionesDt"),
            TableSyncDefinition.Create<INV_PROMOCIONES_DT2>("INV_PROMOCIONES_DT2", "listInvPromocionesDt2", "saveInvPromocionesDt2")
        };

        public static IReadOnlyList<TableSyncDefinition> UploadTables { get; } = new List<TableSyncDefinition>
        {
            TableSyncDefinition.Create<SIS_PARAMETROS>("SIS_PARAMETROS", "listSisParametros", "saveSisParametros"),
            TableSyncDefinition.Create<SIS_SUCURSALES>("SIS_SUCURSALES", "listSisSucursales", "saveSisSucursales"),
            TableSyncDefinition.Create<SIS_DIVISIONES>("SIS_DIVISIONES", "listSisDivisiones", "saveDivisiones"),
            TableSyncDefinition.Create<ACC_CUENTAS>("ACC_CUENTAS", "listAccCuentas", "saveAccCuentas"),
            TableSyncDefinition.Create<ACC_ASIENTOS>("ACC_ASIENTOS", "listAccAsientos", "saveAccAsientos"),
            TableSyncDefinition.Create<ACC_ASIENTOS_DT>("ACC_ASIENTOS_DT", "listAccAsientosDt", "saveAccAsientosDt"),
            TableSyncDefinition.Create<EMP_EMPLEADOS>("EMP_EMPLEADOS", "listEmployess", "saveEmployees"),
            TableSyncDefinition.Create<BAN_BANCOS>("BAN_BANCOS", "listBancos", "saveBancos"),
            TableSyncDefinition.Create<CLI_GRUPOS>("CLI_GRUPOS", "listCliGrupos", "saveCliGrupos"),
            TableSyncDefinition.Create<CLI_RUBROS>("CLI_RUBROS", "listCliRubros", "saveCliRubros"),
            TableSyncDefinition.Create<CLI_CLIENTES>("CLI_CLIENTES", "listClient", "saveCliente"),
            TableSyncDefinition.Create<INV_BODEGAS>("INV_BODEGAS", "listInvBodegas", "saveInvBodegas"),
            TableSyncDefinition.Create<INV_RUBROS>("INV_RUBROS", "listInvRubros", "saveInvRubros"),
            TableSyncDefinition.Create<INV_PRODUCTOS>("INV_PRODUCTOS", "listProducts", "saveProducto"),
            TableSyncDefinition.Create<INV_PRECIOS>("INV_PRECIOS", "listInvPrecios", "saveInvPrecio"),
            TableSyncDefinition.Create<INV_PRECIOS_DT>("INV_PRECIOS_DT", "listInvPreciosDt", "saveInvPrecioDt"),
            TableSyncDefinition.Create<SEG_USUARIOS>("SEG_USUARIOS", "listSegUsuarios", "saveSegUsuarios"),
            TableSyncDefinition.Create<SEG_RECURSOS>("SEG_RECURSOS", "listSegRecursos", "saveSegRecursos"),
            TableSyncDefinition.Create<ACR_RETENCIONES>("ACR_RETENCIONES", "listAcrRetenciones", "saveAcrRetenciones"),
            TableSyncDefinition.Create<ACR_RETENCIONES_DT>("ACR_RETENCIONES_DT", "listAcrRetencionesDt", "saveAcrRetencionesDt"),
            TableSyncDefinition.Create<ACR_RETENCIONES_DEUDAS>("ACR_RETENCIONES_DEUDAS", "listAcrRetencionesDeudas", "saveAcrRetencionesDeudas"),
            TableSyncDefinition.Create<ACR_ACREEDORES_DEUDAS>("ACR_ACREEDORES_DEUDAS", "listAcrAcreedoresDeudas", "saveAcrAcreedoresDeudas"),
            TableSyncDefinition.Create<ACR_CREDITOS>("ACR_CREDITOS", "listAcrCreditos", "saveAcrCreditos"),
            TableSyncDefinition.Create<ACR_CREDITOS_DEUDAS>("ACR_CREDITOS_DEUDAS", "listAcrCreditosDeudas", "saveAcrCreditosDeudas"),
            TableSyncDefinition.Create<ACR_CREDITOS_RUBROS>("ACR_CREDITOS_RUBROS", "listAcrCreditosRubros", "saveAcrCreditosRubros"),
            TableSyncDefinition.Create<ACR_DEBITOS>("ACR_DEBITOS", "listAcrDebitos", "saveAcrDebitos"),
            TableSyncDefinition.Create<ACR_DEBITOS_DEUDAS>("ACR_DEBITOS_DEUDAS", "listAcrDebitosDeudas", "saveAcrDebitosDeudas"),
            TableSyncDefinition.Create<ACR_DEBITOS_RUBROS>("ACR_DEBITOS_RUBROS", "listAcrDebitosRubros", "saveAcrDebitosRubros"),
            TableSyncDefinition.Create<ACR_DEBITOS_PRODUCTOS>("ACR_DEBITOS_PRODUCTOS", "listAcrDebitosProductos", "saveAcrDebitosProductos"),
            TableSyncDefinition.Create<ACR_RECIBOS>("ACR_RECIBOS", "listAcrRecibos", "saveAcrRecibos"),
            TableSyncDefinition.Create<ACR_RECIBOS_DT>("ACR_RECIBOS_DT", "listAcrRecibosDt", "saveAcrRecibosDt"),
            TableSyncDefinition.Create<ACR_RECIBOS_DEUDAS>("ACR_RECIBOS_DEUDAS", "listAcrRecbiosDeudas", "saveAcrRecbiosDeudas"),
            TableSyncDefinition.Create<BAN_DEBITOS>("BAN_DEBITOS", "listBanDebitos", "saveBanDebitos"),
            TableSyncDefinition.Create<BAN_DEBITOS_CUENTAS>("BAN_DEBITOS_CUENTAS", "listBanDebitosCuentas", "saveBanDebitosCuentas"),
            TableSyncDefinition.Create<BAN_DEPOSITOS>("BAN_DEPOSITOS", "listBanDepositos", "saveBanDepositos"),
            TableSyncDefinition.Create<BAN_DEPOSITOS_DT>("BAN_DEPOSITOS_DT", "listBanDepositosDt", "saveBanDepositosDt"),
            TableSyncDefinition.Create<BAN_EGRESOS>("BAN_EGRESOS", "listBanEgresos", "saveBanEgresos"),
            TableSyncDefinition.Create<BAN_EGRESOS_ANEXOS>("BAN_EGRESOS_ANEXOS", "listBanEgresosAnexos", "saveBanEgresosAnexos"),
            TableSyncDefinition.Create<BAN_EGRESOS_ANTICIPOS>("BAN_EGRESOS_ANTICIPOS", "listBanEgresosAnticipos", "saveBanEgresosAnticipos"),
            TableSyncDefinition.Create<BAN_EGRESOS_CUENTAS>("BAN_EGRESOS_CUENTAS", "listBanEgresosCuentas", "saveBanEgresosCuentas"),
            TableSyncDefinition.Create<BAN_EGRESOS_DEUDAS>("BAN_EGRESOS_DEUDAS", "listBanEgresosDeudas", "saveBanEgresosDeudas"),
            TableSyncDefinition.Create<BAN_EGRESOS_DT>("BAN_EGRESOS_DT", "listbanEgresosDt", "savebanEgresosDt"),
            TableSyncDefinition.Create<BAN_EGRESOS_PAGOS>("BAN_EGRESOS_PAGOS", "listbanEgresosPagos", "savebanEgresosPagos"),
            TableSyncDefinition.Create<BAN_INGRESOS>("BAN_INGRESOS", "listBanIngresos", "saveBanIngresos"),
            TableSyncDefinition.Create<BAN_INGRESOS_CUENTAS>("BAN_INGRESOS_CUENTAS", "listbanIngresosCuentas", "savebanIngresosCuentas"),
            TableSyncDefinition.Create<BAN_INGRESOS_DEUDAS>("BAN_INGRESOS_DEUDAS", "listBanIngresosDeudas", "saveBanIngresoDeuda"),
            TableSyncDefinition.Create<BAN_INGRESOS_DT>("BAN_INGRESOS_DT", "listBanIngresosDt", "saveBanIngresosDt"),
            TableSyncDefinition.Create<BAN_PAPELETAS>("BAN_PAPELETAS", "listbanPapeletas", "savebanPapeletas"),
            TableSyncDefinition.Create<BAN_INGRESOS_PINPAD>("BAN_INGRESOS_PINPAD", "listBanIngresosPinPad", "saveBanIngresoPinpad"),
            TableSyncDefinition.Create<BAN_INGRESOS_TARJETAS>("BAN_INGRESOS_TARJETAS", "listbanIngresosTarjetas", "savebanIngresosTarjetas"),
            TableSyncDefinition.Create<BAN_TRANSFERENCIAS>("BAN_TRANSFERENCIAS", "listbanTransferencias", "savebanTransferencias"),
            TableSyncDefinition.Create<BAN_TRANSFERENCIAS_DT>("BAN_TRANSFERENCIAS_DT", "listbanTransferenciasDt", "savebanTransferenciasDt"),
            TableSyncDefinition.Create<VEN_FACTURAS>("VEN_FACTURAS", "listVenFacturas", "saveVenFacturas"),
            TableSyncDefinition.Create<VEN_FACTURAS_PAGOS>("VEN_FACTURAS_PAGOS", "listvenFacturasPagos", "savevenFacturasPagos"),
            TableSyncDefinition.Create<VEN_FACTURAS_DT>("VEN_FACTURAS_DT", "listVenFacturasDt", "saveVenFacturasDt"),
            TableSyncDefinition.Create<COM_FACTURAS>("COM_FACTURAS", "listComFacturas", "saveComFacturas"),
            TableSyncDefinition.Create<COM_FACTURAS_DT>("COM_FACTURAS_DT", "listComFacturasDt", "saveComFacturasDt"),
            TableSyncDefinition.Create<COM_FACTURAS_PAGOS>("COM_FACTURAS_PAGOS", "listComFacturasPagos", "saveComFacturasPagos"),
            TableSyncDefinition.Create<INV_PRODUCTOS_PRECIOS>("INV_PRODUCTOS_PRECIOS", "listPriceProducts", "savePriceProducts"),
            TableSyncDefinition.Create<INV_PRODUCTOS_EMPAQUES>("INV_PRODUCTOS_EMPAQUES", "listPackagesProducts", "savePackageProductos"),
            TableSyncDefinition.Create<INV_EGRESOS>("INV_EGRESOS", "listinvEgresos", "saveinvEgresos"),
            TableSyncDefinition.Create<INV_EGRESOS_RUBROS>("INV_EGRESOS_RUBROS", "listinvEgresosRubros", "saveinvEgresosRubros"),
            TableSyncDefinition.Create<INV_EGRESOS_PRODUCTOS>("INV_EGRESOS_PRODUCTOS", "listinvEgresosProductos", "saveinvEgresosProductos"),
            TableSyncDefinition.Create<INV_INGRESOS>("INV_INGRESOS", "listinvIngresos", "saveinvIngresos"),
            TableSyncDefinition.Create<INV_INGRESOS_PRODUCTOS>("INV_INGRESOS_PRODUCTOS", "listinvIngresosProductos", "saveinvIngresosProductos"),
            TableSyncDefinition.Create<INV_PRODUCTOS_CARDEX>("INV_PRODUCTOS_CARDEX", "listInvProductosCardex", "saveInvProductosCardex"),
            TableSyncDefinition.Create<INV_TRANSFERENCIAS>("INV_TRANSFERENCIAS", "listInvTransferencias", "saveInvTransferencias"),
            TableSyncDefinition.Create<INV_TRANSFERENCIAS_DT>("INV_TRANSFERENCIAS_DT", "listInvTransferenciasDt", "saveInvTransferenciasDt"),
            TableSyncDefinition.Create<POS_CIERRES>("POS_CIERRES", "listPosCierre", "savePosCierres"),
            TableSyncDefinition.Create<POS_CIERRES_CAJA>("POS_CIERRES_CAJA", "listPosCierresCaja", "savePosCierresCajas"),
            TableSyncDefinition.Create<POS_TRANSFERENCIAS>("POS_TRANSFERENCIAS", "listPosTransferencias", "savePosTransferencias"),
            TableSyncDefinition.Create<POS_TRANSFERENCIAS_DT>("POS_TRANSFERENCIAS_DT", "listPosTransferenciasDt", "savePosTransferenciasDt"),
            TableSyncDefinition.Create<PRV_FACTURAS>("PRV_FACTURAS", "listPrvFacturas", "savePrvFacturas"),
            TableSyncDefinition.Create<PRV_FACTURAS_DT>("PRV_FACTURAS_DT", "listPrvFacturasDt", "savePrvFacturasDt"),
            TableSyncDefinition.Create<PRV_FACTURASCTA_DT>("PRV_FACTURAS_CTA_DT", "listPrvFacturasCtaDt", "savePrvFacturasCtaDt"),
            TableSyncDefinition.Create<CLI_CLIENTES_DEUDAS>("CLI_CLIENTES_DEUDAS", "listClientesDeduas", "saveClienteDeudas"),
            TableSyncDefinition.Create<CLI_CREDITOS>("CLI_CREDITOS", "listCliCreditos", "saveCliCreditos"),
            TableSyncDefinition.Create<CLI_CREDITOS_DEUDAS>("CLI_CREDITOS_DEUDAS", "listCliCreditosDeudas", "saveCliCreditosDeudas"),
            TableSyncDefinition.Create<CLI_CREDITOS_RUBROS>("CLI_CREDITOS_RUBROS", "listCliCreditosRubros", "saveCliCreditosRubros"),
            TableSyncDefinition.Create<CLI_CREDITOS_PRODUCTOS>("CLI_CREDITOS_PRODUCTOS", "listCliCreditosProductos", "saveCliCreditosProductos"),
            TableSyncDefinition.Create<CLI_DEBITOS>("CLI_DEBITOS", "listCliDebitos", "saveCliDebitos"),
            TableSyncDefinition.Create<CLI_DEBITOS_RUBROS>("CLI_DEBITOS_RUBROS", "listCliDebitosRubros", "saveCliDebitosRubros"),
            TableSyncDefinition.Create<CLI_RETENCIONES>("CLI_RETENCIONES", "listCliRetenciones", "saveCliRetenciones"),
            TableSyncDefinition.Create<CLI_RETENCIONES_DT>("CLI_RETENCIONES_DT", "listCliRetencionesDt", "saveCliRetencionesDt"),
            TableSyncDefinition.Create<CLI_RETENCIONES_DEUDAS>("CLI_RETENCIONES_DEUDAS", "listCliRetencionesDeudas", "saveCliRetencionesDeudas"),
            TableSyncDefinition.Create<INV_EMPAQUES>("INV_EMPAQUES", "listInvPackages", "saveInvPackages"),
            TableSyncDefinition.Create<SEG_PERFILES>("SEG_PERFILES", "listSegProfiles", "saveSegProfiles"),
            TableSyncDefinition.Create<INV_COMBOS>("INV_COMBOS", "listComboProducts", "saveCombos"),
            TableSyncDefinition.Create<INV_COMBOS_COMPONENTES>("INV_COMBOS_COMPONENTES", "listComboComponentesProducts", "saveComboComponente"),
            TableSyncDefinition.Create<SRI_SECUENCIAL>("SRI_SECUENCIAL", "listSriSecuencial", "saveSriSecuencial"),
            TableSyncDefinition.Create<SEG_PERFILES_RECURSOS>("SEG_PERFILES_RECURSOS", "listSegPerfilesRecursos", "saveSegPerfilesRecursos"),
            TableSyncDefinition.Create<EMP_DEBITOS>("EMP_DEBITOS", "listEmpDebitos", "saveEmpDebitos"),
            TableSyncDefinition.Create<EMP_EMPLEADOS_DEUDAS>("EMP_EMPLEADOS_DEUDAS", "listEmpEmpleadosDeudas", "saveEmpEmpleadosDeudas"),
            TableSyncDefinition.Create<BAN_BANCOS_CARDEX>("BAN_BANCOS_CARDEX", "listBanBancosCardex", "saveBanBancosCardex"),
            TableSyncDefinition.Create<EMP_DEBITOS_RUBROS>("EMP_DEBITOS_RUBROS", "listEmpDebitosRubros", "saveEmpDebitosRubros"),
            TableSyncDefinition.Create<BAN_CREDITOS>("BAN_CREDITOS", "lisBanCreditos", "saveBanCreditos"),
            TableSyncDefinition.Create<BAN_CREDITOS_CUENTAS>("BAN_CREDITOS_CUENTAS", "lisBanCreditosCuentas", "saveBanCreditosCuentas"),
            TableSyncDefinition.Create<ORG_BUZONES>("ORG_BUZONES", "listOrgBuzones", "saveOrgBuzones"),
            TableSyncDefinition.Create<ORG_DOCUMENTOS>("ORG_DOCUMENTOS", "listOrgDocumentos", "saveOrgDocumentos"),
            TableSyncDefinition.Create<ORG_TAREAS>("ORG_TAREAS", "listOrgTareas", "saveOrgTareas")
        };
    }
}
